### ISSUE TITLE
feature request: keymap for kernel commands

### ISSUE THREAD

**Issue by kengz** [nteract/hydrogen#1038]
In some jupyter package one can interrupt and restart kernel with hotkey like `I,I` or `O,O` respectively.

I find myself doing kernel kill and restart a lot when developing on Hydrogen. Would be nice to have mappable keymap instead of having to use the command palette.

Requesting keymap for the existing commands:
- interrupt kernel
- shutdown kernel
- restart kernel
- restart kernel and evaluate

**Comment by lgeiger** [comment]
Generally speaking I'm not sure if we should add too many keymaps in order to not conflict with other packages.

What keymaps are you thinking about adding for these commands?

You can always customize the keybindings via your user keymaps file: http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings

**Comment by kengz** [comment]
Oh okay I didn't realize you could add keymap to command not already declared! Here's it working:

```
  'ctrl-enter': 'hydrogen:run'
  'ctrl-shift-enter': 'hydrogen:run-all'
  'ctrl-backspace': 'hydrogen:clear-results'
  'ctrl-shift-backspace': 'hydrogen:restart-kernel'
`in

Thanks for pointing that out. Feel free to close The issue.

**Comment by jerry-repo-03** [comment]
thanks
