### ISSUE TITLE
Hotkey conflict

### ISSUE THREAD

**Issue by suatatan** [nteract/hydrogen#1059]
**Description:**

After installing Hydrogen package to Atom Editor my ctrl-c hotkey started to does not work. I noticed from keybinding resolver one of the Hydrogen command (interrupt kernel) uses ctrl-c either. By the way, I had to uninstall it and removed this lines from cson files.

**Versions:**
Atom 1.2.11, Hydrogen: last, OS. Win 10

**Comment by lgeiger** [comment]
That's strange. Hydrogen shouldn't add `ctrl-c` to the keybindings by it self. Checkout the [list of keymaps]( https://github.com/nteract/hydrogen/blob/master/keymaps/hydrogen.cson).

> Atom 1.2.11

Do you mean Atom 1.21.1? Atom 1.2 almost two years old. This would imply that Hydrogen is very too, since it requires a fairly recent version of Atom.

**Comment by BenRussert** [comment]
I can say with full certainty that this is not caused by the hydrogen install itself. 

It's possible the keymap is coming from another package or personal keymap file. I'd recommend reinstalling hydrogen in case the install was modified locally. Also check apm links if you may have created a Dev version and added this to the keymap. 

Let us know if you have questions!

**Comment by suatatan** [comment]
I applied 'Checkout the list of keymaps' advice of @lgeiger  and it worked. Maybe another package caused the problem like @BenRussert. There was no version problem.
