### ISSUE TITLE
filepath autocompletion

### ISSUE THREAD

**Issue by HenrikEckermann** [nteract/hydrogen#1195]
Hi,

is it possible to enable file path autocompletion? In RSTUDIO if I e.g. type

`setwd('user/example...')`

then I could press tab and it picks the matching folder/file if there is one. Would be cool if hydrogen will support that soon or in case I can enable it, please someone give me a hint. 

Thanks!

**Comment by nikitakit** [comment]
Thanks for reporting!

I looked into why this is happening, and it turns out that hydrogen isn't really using the full power of the Jupyter protocol to do autocomplete. The protocol is designed to accept a code block and a cursor position, and output completions. Hydrogen instead using a custom regex to send the kernel a completion string (with the cursor position field always set to the end of the string). Moreover, hydrogen disables autocomplete inside strings.

Fixing this seems like it would take a bit of work, but the good news is that it's language-independent and can bring other benefits besides path completion (e.g. completion of dictionary keys)

**Comment by kashuk** [comment]
Any update on this? Thanks!

**Comment by kylebarron** [comment]
This is already fixed, at least for Python

**Comment by kashuk** [comment]
Thanks Klye for your prompt reply. I am new to Hydrogen so might miss something here. In Jupiter Notebook, when I write "/U" and tab it will autocomplete to "/Users" but when I do it In Hydrogen, I have to write "/Use" and then it will give me a couple of options including the "/User" but not as the first option. If that is what I suppose to get then that is okay. I just wanted to double check. Thanks again!

**Comment by kylebarron** [comment]
You can change the number of characters needed to generate autocomplete suggestions in the settings for `autocomplete-plus`. There might be autocomplete suggestions from other packages listed before the Hydrogen ones. It's  hard to tell without a screenshot

**Comment by kashuk** [comment]
Great! I already changed it and it feels much better. Thanks for the tip! here is the screenshot:
<img width="378" alt="screen shot 2019-02-13 at 10 14 40 am" src="https://user-images.githubusercontent.com/12432685/52736106-e7ed0b00-2f7d-11e9-8c4d-3660d6456eb3.png">

**Comment by wadethestealth** [comment]
@kashuk 
```javascript
    inclusionPriority: 1,
    suggestionPriority: atom.config.get("Hydrogen.showAutocompleteFirst")
      ? 3
      : 1,
    excludeLowerPriority: false,
```
you can change this code inside of hydrogens `autocomplete-provider.js` file, but in your config you should be be able to set showAutocompleteFirst to true to make it appear first
(docs to the autocomplete provider code)[https://github.com/atom/autocomplete-plus/wiki/Provider-API]
