### ISSUE TITLE
Export Notebook - markdown cells not correctly exported to ipynb

### ISSUE THREAD

**Issue by dynobo** [nteract/hydrogen#1296]
**Description:**

When exporting a py-File to ipynb-File the Markdown-Cells are exported as Code-Cells, not as Markdown cells. 

**Steps to Reproduce:**

1. Copy the following code to a new py-File:
```
#%%
print('hello world')

#%%markdown
# # Headline1
# - bullet point
# **bold text**

# %%
print('bye world')
```

2. Run "Hydrogen - Export Notebook"

3. Open the created ipynb-File in Jupyter Notebook, you'll see:

![screen1](https://user-images.githubusercontent.com/11071876/39092766-1d380196-4615-11e8-992d-a2fb34f0ffa0.png)

Expected would be a markdown cell:

![screen2](https://user-images.githubusercontent.com/11071876/39092775-3e334f7c-4615-11e8-87a6-ff69921ba870.png)

**Versions:**
Hydrogen 2.4.1
Atom 1.25.1
Running on Solus Linux
Which OS and which version of Hydrogen and Atom are you running?

**Logs:**
*not relevant*

**Comment by Madhu94** [comment]
Picking this up, as I made the original PR for exporting to notebook.

**Comment by Madhu94** [comment]
@dynobo Is the "%%markdown" syntax expected to be like the ipython's "%%markdown" cell magic ? I think in that case, the expected output would be this ?

![image](https://user-images.githubusercontent.com/9015820/42131700-fb1f08a0-7d25-11e8-9287-95d374d01dcf.png)

**Comment by dynobo** [comment]
@Madhu94 
No, not really. I would expect it to me converted into a [cell of type "markdown"](https://ipython.org/ipython-doc/3/notebook/nbformat.html#markdown-cells). After running a cell of this type, the source code vanishs and only the rendered markdown stays visible. 

For an example, see the text in this shot of a notebook. The first two cells ("Jupyter Notebook Slides.." and "Overview" are those markdown cells: 
![notebook](https://cdn-images-1.medium.com/max/1600/1*kt_bEri7QAArBhP1qPJgMg.png)

**Comment by Madhu94** [comment]
My mistake, I thought ``%%markdown`` was a magic like ``%%javascript``. I just wondered where the "%%markdown" syntax came from; I couldn't find it in the Hydrogen docs either.

**Comment by dynobo** [comment]
@Madhu94: I stumbled upon it through the "rich document" feature, described shortly on the [bottom of this page](https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html). I expected the markdown-parts of such an document to be exported as markdown-cells even without "%%markdown" syntax (this would be my favourite solution), but as it didn't do this, it thought at least the markdown syntax might be handled.

But I want to give a bit background:

I like a lot the [R-Notebooks](https://blog.rstudio.com/2016/10/05/r-notebooks), which allow to mix Code and Markdown in the same file. There, I can write everything from top to bottom in a single text file in my IDE, and it can also be read in every simple Text-Editor. In e.g. Jupyter I have to deal with cells, and I need a notebook viewer to render the content. 

Hydrogen, with "Rich documents" is just soooo close to filling this need, which would be really cool. Unfortunately, as long as a Hydrogen is not "the standard", such a feature still would be quite worthless without being able to export such a Rich Document to Jupyter, so I can share it in my university class or something...

So, if the markdown-parts of a "Rich document" would be rendered as jupyter-markdown-cells (with, or even better without %%markdown), this would be so perfect. I guess other people knowing R-Notebooks might feel the same... :-)

**Comment by kylebarron** [comment]
@dynobo You might want to try the [pweave](http://mpastell.com/pweave/docs.html) package. It was modeled after R Markdown and lists jupyter notebooks as one of its output formats, though I haven't tested that part.

**Comment by kylebarron** [comment]
I'm interested in taking a closer look at this, though I'm about to go on vacation for a week and a half.

It seems like it's currently a simple wrapper around `stringifyNotebook`. So would a fix be done in nteract/commutable instead of here?
https://github.com/nteract/hydrogen/blob/3291db2e4f91d311b392e60599e05687ec1839e6/lib/export-notebook.js#L19

**Comment by mwouts** [comment]
Hello @dynobo, I see you have previous experience with R markdown notebooks. Have you ever tried to open these documents with Jupyter? There are a few plugins around that allow this. I recommend in particular [notedown](https://github.com/aaren/notedown) (many GitHub stars) and [jupytext](https://github.com/mwouts/jupytext/) (my contribution). 

Are you able to run python cells in markdown or R markdown documents in Hydrogen? If yes, you could experiment editing these documents simultaneously in Hydrogen and Jupyter (run `%autosave 0` if you open both editors at the same time, and use Ctrl+R to reload from file while preserving kernel).

**Comment by kiwi0fruit** [comment]
Does this work in Hydrogen export to ipynb?

```py
# <markdowncell>
# # Headline1
# - bullet point
# **bold text**
```
As nbconvert seems to support that: http://ipython.org/ipython-doc/2/notebook/nbconvert.html#notebook-json-file-format

**Comment by mwouts** [comment]
Hello @kiwi0fruit , I think there are plans to support this in Hydrogen at some point. For now you can use an independent program named `jupytext` (I am the main author). Jupytext does support the double percent cells syntax (this is documented [here](https://towardsdatascience.com/jupyter-notebooks-as-light-percent-or-sphinx-scripts-efca8bc3aa44)). Markdown cells are defined like this:
```
# %% [markdown]
# Content of 
# markdown cell
```

**Comment by kylebarron** [comment]
I think I've narrowed down the issue in Hydrogen. `Hydrogen:export-notebook` calls `exportNotebook()` [here](https://github.com/nteract/hydrogen/blob/master/lib/export-notebook.js), which is mostly boilerplate around

```js
JSON.stringify(store.notebook, null, 2)
```

So the issue here is in `store.notebook`. The definition of `.notebook` is:
https://github.com/nteract/hydrogen/blob/1a41f824e08305415e412061483c18f145a984a7/lib/store/index.js#L66-L83

To me, it appears the issue is likely in `codeManager.getCells(editor);`. That probably generates cell ranges that include comments in the code blocks, and there probably needs to be a way to divide the cell ranges into Markdown blocks as well.

**Comment by kylebarron** [comment]
Actuall the `codeManager.getCells(editor);` is fine. It's the `commutable.emptyCodeCell` that needs to be changed. It needs to be `emptyMarkdownCell` for cells that started with `# %% markdown`. This might require a change to `getCells`, since I don't think it currently returns the text next to `%%`.

**Comment by mwouts** [comment]
Hello @kylebarron , I think we should use compatible specifications across the multiple implementations of the text to jupyter notebook converters. 

May I suggest that Hydrogen could use `# %% [markdown]` for marking markdown cells? That syntax was suggested by the Spyder team at https://github.com/spyder-ide/spyder/issues/7933, and that's the one implemented in `jupytext`. 

See also the [documentation](https://github.com/mwouts/jupytext/blob/master/README.md#the-percent-format) for the `percent` format in `jupytext`, or this
 [review](https://towardsdatascience.com/jupyter-notebooks-as-light-percent-or-sphinx-scripts-efca8bc3aa44) of script formats for notebooks. Interestingly the `percent` format is supported beyond Hydrogen and Spyder, in as many as five Python editors!

**Comment by kiwi0fruit** [comment]
I think block comment way is more convenient for one way conversion (hydrogen to ipynb). Like here : https://github.com/nojvek/vscode-ipynb-py-converter#example

```py
# %%
'''
# Header

text.
'''

# %%
print('hello')
```

**Comment by kylebarron** [comment]
Well in the long term I think it's optimal to have two-way conversion in Hydrogen, both to and from `.ipynb` files.

To me, those multiline strings are problematic because 
1) They get run by the Python interpreter. I'm guessing that usually that isn't a problem, but it's probably still best to keep Markdown text in block comments.
2) That prevents being able to use `hydrogen:run-and-move-down` to cleanly run through all code.

**Comment by kiwi0fruit** [comment]
If we speak about python only then two way conversion is possible
(stringify to python strings). But there would be problems on other
languages.

Yep, it's more difficult to implement. Your second concern adds to this
(first one does not matter).

>

**Comment by mwouts** [comment]
Thanks @kylebarron , @kiwi0fruit ! It's good to have this conversation. 
> What about Hydrogen having a superset?

Well, if you choose a superset that we can also implement in `jupytext`, I will be glad to follow your standard. Not on `markdown` however because that's hard to distinguish from the cell title used by Spyder. But I have no objection to `<markdown>` or `<md>`. By the way, do you plan to support raw cells?

> I think block comment way is more convenient for one way conversion

The Spyder team also suggested to represent markdown cells as multiline strings - they like the potential for using f-strings. And Sphinx-Galleries also offer markdown cells as multiline strings. However, we have not yet implemented support for these multiline strings in `jupytext`, and I am not sure we will, because of the following reasons
- multiline strings are Python specific
- and they are more difficult to parse than commented lines, especially in Hydrogen's case, when the parser has to be developed in Javascript.

**Comment by kiwi0fruit** [comment]
If you want to make it comfortable with in-line comments then you can add
Atom hot keys 'uncomment cell' and 'comment cell'.

>

**Comment by kiwi0fruit** [comment]
Any language with block comments can be used with block comments instead of
in-line comments the very same way. Not any markdown text can be encoded
though. Cases that cannot be encoded via block comments can always be
encoded via in-line comments.

>

**Comment by kylebarron** [comment]
Sorry, I edited my previous post a bit too extensively after posting...

I think one of the best and most important features of Hydrogen is its total language agnosticness. I don't think any of the maintainers want to add something to Hydrogen that only works for Python.

> By the way, do you plan to support raw cells?

Not in the short term, theoretically in the long term, but it really depends if there's a desire for it in the community.

**Comment by kiwi0fruit** [comment]
In addition to [vscode-ipynb-py-convert](https://github.com/nojvek/vscode-ipynb-py-converter) the block commented Markdown cells are supported by [pandoctools](https://github.com/kiwi0fruit/pandoctools) (that uses [knitty](https://github.com/kiwi0fruit/knitty) that uses [stitch](https://github.com/pystitch/stitch)). And the `# %%` format supported by pandoctools is convertable to stitch format.
