### ISSUE TITLE
shell message.content.payload is ignored (causing IRkernel ?foo/help(foo) to return no result)

### ISSUE THREAD

**Issue by jdanbrown** [nteract/hydrogen#1304]
I'm seeing a funny behavior with IRkernel where `?foo` / `help(foo)` doesn't return a result. (Convo moved in from https://nteract.slack.com/archives/C4S4H8DN1/p1525387222000158.)

I think the root of the problem is:
- There's no `output_type: 'display_data'` or `output_type: 'stream'` msg, like for usual outputs
- IRkernel is sending the help result on the `shell` channel in `message.content.payload[0]` and Hydrogen isn't looking for messages there (as per https://github.com/nteract/hydrogen/blob/master/lib/kernel.js#L323-L334)
```json
{
  "idents": [],
  "header": {...},
  "parent_header": {...},
  "metadata": {},
  "content": {
    "status": "ok",
    "execution_count": 2,
    "payload": [
      {
        "source": "page",
        "data": {
          "text/html": "No documentation for 'foo' in specified packages and libraries:\nyou could try '??foo'",
          "text/latex": "No documentation for 'foo' in specified packages and libraries:\nyou could try '??foo'",
          "text/plain": "No documentation for 'foo' in specified packages and libraries:\nyou could try '??foo'"
        },
        "metadata": {}
      }
    ],
    "user_expressions": {}
  },
  "buffers": []
}
```

But `jupyter console` does manage to find the payload from the 'shell' channel, somehow:
```R
$ jupyter console --kernel=ir

In [1]: ?foo
No documentation for 'foo' in specified packages and libraries:
you could try '??foo'

In [2]: help(foo)
No documentation for 'foo' in specified packages and libraries:
you could try '??foo'
```

**Versions:**
- Hydrogen 2.4.1
- IRkernel 0.8.11

**Comment by nikitakit** [comment]
This is the same issue as #1301. At the moment the only supported way of getting help messages about objects is by using the "Hydrogen: Toggle Inspector" command.

That said I think we should keep the issue in mind, because (a) incompatibility with other frontends is a problem and (b) the current inspector doesn't emulate the behavior of `??` in IPython, only the behavior of `?`.

**Comment by n-riesco** [comment]
Just for the record, [payloads are deprecated](https://jupyter-client.readthedocs.io/en/stable/messaging.html#payloads-deprecated).

**Comment by jdanbrown** [comment]
Also worth noting that we seem to be stuck with them anyway:

> Payloads are considered deprecated, though their replacement is not yet implemented.

And thanks for the pointer to that section of the docs—it explains what `"source": "page"` is in the `shell` msg at top:

> page: display data in a pager.
>
> Pager output is used for introspection, or other displayed information that’s not considered output. Pager payloads are generally displayed in a separate pane, that can be viewed alongside code, and are not included in notebook documents.

**Comment by nikitakit** [comment]
That message in the spec really dissuaded me from trying to implement payload support the last time I thought about it. However, "their replacement is not yet implemented" is not quite true. Hydrogen's `Toggle Inspector` is sufficient for help messages.

The problem is that:
* Patterns and muscle memory from other frontends don't work in the current version of hydrogen
* The `Toggle Inspector` command always sends `detail_level = 0`, but there needs to be an option to send `detail_level = 1` to emulate the behavior of `??` in IPython.

**Comment by jdanbrown** [comment]
> Patterns and muscle memory from other frontends don't work in the current version of hydrogen

Yeah, and I'd push that point a little further: supporting the payload msgs is helpful for users who prefer to see content inline instead of in the bottom dock, i.e. would prefer to see the results of `foo?` as normal output instead of in the inspector.

**Comment by kylebarron** [comment]
If payloads are deprecated, couldn't irkernel switch the messages from payload to `display_data` or `stream`?
