### ISSUE TITLE
Run all code up to current line

### ISSUE THREAD

**Issue by onyxfish** [nteract/hydrogen#132]
I'd like to add a command to run all code up to the current cursor line. I'm thinking of mapping it to "Ctrl + Alt + Cmd + Enter". Thoughts?

**Comment by willwhitney** [comment]
This would be nice to have. 

Maybe by default it shouldn't be mapped to a keyboard shortcut — I don't want to fill up that space too much, since I think lots of people only use Hydrogen occasionally. That way people like us who would use this command a lot can define a shortcut without it getting in the way for others.

That being said, it's probably not a big deal either way.

Rock on!

**Comment by terraqout** [comment]
Don't you prefer to just bind some key for selecting part of file?
In vim-mode it's just ```vgg``` other editors should do something look like.
And nobody don't like unexpected keybindings that remaps their own.

**Comment by willwhitney** [comment]
I agree in principle with having selection and execution separate, but a
couple of people have asked for versions of this.

Let's add the command but not a default keybinding.

**Comment by onyxfish** [comment]
Sounds good. I'll take a crack at it when I have a little time.

**Comment by edwinksl** [comment]
This would be a great feature. It can be a hassle to select and run large chunks of code.

**Comment by willwhitney** [comment]
@onyxfish how's the new job going? Still interested in knocking this together sometime?

**Comment by lgeiger** [comment]
https://github.com/nteract/hydrogen/pull/165
