### ISSUE TITLE
Invalid syntax error when using python hydrogen atom

### ISSUE THREAD

**Issue by osakada** [nteract/hydrogen#1353]
Using Atom-editor python Hydrogen.
I caught error "Invalid Syntax." (pic1 below)
I didn't caught the error when using pycharm editor.
Why does this error occur? 

Anybody, please help!

**Error**
![pics21](https://user-images.githubusercontent.com/7657468/42336470-bc8b9710-80be-11e8-9598-4872a1553ccf.JPG)

**Installed Packages**
![pics22](https://user-images.githubusercontent.com/7657468/42336474-c0385c40-80be-11e8-8bad-7c812509dfe7.JPG)
![pics23](https://user-images.githubusercontent.com/7657468/42336478-c3283e16-80be-11e8-8b40-0a2368d9b047.JPG)

**Versions:**
Windows 8.1
Hydrogen 2.5.1
atom 1.28.1 x64

**Comment by nikitakit** [comment]
Hydrogen is designed to support all programming languages, so you need to be somewhat precise in selecting what code to run. If your cursor is on line 22 and you select the standard "run" command, figuring out whether you actually meant to run all of lines 20-25 requires complicated python-specific logic that is not implemented.

Instead, Hydrogen just runs the line you're on and any indented code block that follows:
```python
elif guess_me > 7:
    print('too high')
```

This is a SyntaxError because there is no corresponding `if` statement.

You can instead directly select lines 20-25 and run the selection, which will cover the branch of `if/elif/else` that applies. You can also use [code cells](https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html#hydrogen-run-cell) to avoid selecting code every time.

**Comment by BenRussert** [comment]
Looks like the above comment covers it, thanks!
