### ISSUE TITLE
Python - OLS Regresson results summary - Text Alignment issues on hydrogen output window

### ISSUE THREAD

**Issue by sjvaidya** [nteract/hydrogen#1366]
**Description:**
Text Alignment issues with OLS Regression result summary in hydrogen-output. Things get messy to interpret without alignment. Please refer two screenshot for more details.

Note:- This works fine when the results are displayed inline

Code:

import pandas as pd
import numpy as np
import statsmodels.api as sm

data_train = pd.read_csv('train.csv')
data_train.columns.values

y = data_train[['SalePrice']]
X = data_train[['GrLivArea'] + ['TotalBsmtSF']]

X1 = sm.add_constant(X)

print(sm.OLS(y,X1).fit().summary())

**Steps to Reproduce:**

1. Run python code to Display OLS Regression results summary inline
2. From settings, enable hydrogen output window
2. Run python code to Display OLS Regression results summary again
3. See the text/data alignments in both cases.

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Win10, Atom 1.28.1 x64
![hydrogen-inline-results](https://user-images.githubusercontent.com/29955169/43519558-8d482186-95ad-11e8-8442-b1c52dace5d1.png)
![hydrogen-output-text-misaligned](https://user-images.githubusercontent.com/29955169/43519559-8d73d68c-95ad-11e8-84ef-3bdd6cb01470.png)

**Comment by bigheadming** [comment]
I have the same problem when using show command in pyspark. Can you please fix it, or allow the user to choose the font-family in output area? Thanks.

peopleDF.show(truncate=False)

+-----------------------+-------+------------------------------------+
|cities                 |name   |schools                             |
+-----------------------+-------+------------------------------------+
|[palo alto, menlo park]|Michael|[[stanford, 2010], [berkeley, 2012]]|
|[santa cruz]           |Andy   |[[ucsb, 2011]]                      |
|[portland]             |Justin |[[berkeley, 2014]]                  |
+-----------------------+-------+------------------------------------+

**Comment by BenRussert** [comment]
This needs a stylesheet tweak. This is a great first issue and if one of you decide to look into it you probably will not even need an understanding of javascript to take this on.

I will answer any questions I can and would be so grateful if you took a crack at fixing this :bowing_man: 

To start, check out how to start your own [development copy](https://github.com/nteract/hydrogen/blob/master/CONTRIBUTING.md) of hydrogen. From there you can edit the `hydrogen.less` file and if you started atom in dev mode with `atom -d .` the style changes will live update so you can mess around until you get the hang of it!

I would start by looking at [this line in our stylesheet](https://github.com/nteract/hydrogen/blob/master/styles/hydrogen.less#L241). I would google around to find out what style properties to change in order to fix text alignment and see if we might be doing this wrong someplace in that file.

Next, if that didnt work (though I think it will), you would want to look at the [output-area component](/home/ben/Documents/hydrogen/lib/components/output-area.js)

**Comment by kylebarron** [comment]
@bigheadming The reason it's not working for you is because you have invalid JSON. Correct your {} levels and it'll work. For any followup questions please open a different issue and you can tag me if you want.

```json
[{
"name": "Jupyter Book - Python",
"options": {
"baseUrl": "http://localhost:8889",
"token": "xxx"
},
{
"name": "Jupyter Book - Scala",
"options": {
"baseUrl": "http://localhost:8890",
"token": "xxx"
}
}]
```

**Comment by bigheadming** [comment]
Hi, here are some updates. First, to resolve the alignment problem in the output area, I put font-family: monospace under the .output-area .multiline-container. However, I find another problem when an error returns. As you can see in the picture below, the red color and blue color error text (there is blue color message after the get_return value) can't be seen clearly.
![bad](https://user-images.githubusercontent.com/31396275/44298626-111d2f00-a2ac-11e8-83f7-5c243f328cb5.PNG)
After struggling for a while (yes, a lot of time). I end up changing the background color in the .output-area .multiline-container in order to see all the 'beautiful' colored error message, using the settings below: 

.hydrogen .output-area {
  color: darken(white, 15%);
  .multiline-container {
    font-family: monospace;
    //text-align: center;
    background-color: darken(darkgrey, 15%);
    //color: darken(white, 20%);
  }
  .nteract-display-area-traceback {
    color: darken(white, 15%);
  }
}
The error in the output area looks like this now: 

![better](https://user-images.githubusercontent.com/31396275/44298672-c223c980-a2ac-11e8-905d-508cebd9eade.PNG)

Here is the fix for the alignment:
![image](https://user-images.githubusercontent.com/31396275/44298691-0ca54600-a2ad-11e8-9aee-4a01672a2155.png)


The color error message issue is where I spent most of my time trying. Frankly, I don't like the grey background given all else are in black color. But there is the best color I can find in order to see the 'beautiful' green, blue and red error messages. 

The reason for the returned color error message may be from default color of  jupyter notebook. As seen below, it returns a html with color preset: 
![image](https://user-images.githubusercontent.com/31396275/44298726-c8ff0c00-a2ad-11e8-830a-406144541a0b.png)

I tried to include a custom.css in .jupyter directory and passed the custom.css when starting the jupyter server (by adding c.NotebookApp.extra_static_paths = ['/home/xxx/.jupyter/custom'] in jupyter_notebook_config.py). In a browser, the notebook comes out beautiful with all color I want. However, when doing it hydrogen, it stays the same no matter what I tried. 

Anyone, please see if you can help me to fix the problem by altering the colored error message return by Jupyter. Thanks in advance. 

BTW, text-align: center works, but I disable it as I don't know the output in center. 

Another issue I found is that the slide bar on the output area is not working. It is supposed that I can click and drag the 'square' so that I can see the output one by one. But it doesn't work. The only way is to use the '<' and '>' at both ends of the slide bar to see the output one by one. 
![image](https://user-images.githubusercontent.com/31396275/44298782-e680a580-a2ae-11e8-8a72-1853bee37616.png)

**Comment by gabrielfilipe7unb** [comment]
with open('summary.txt', 'w') as fh:
    fh.write(model.summary().as_text())
