### ISSUE TITLE
Allow for autocomplete to be provided within string scope for some languages

### ISSUE THREAD

**Issue by kylebarron** [nteract/hydrogen#1383]
I'm developing a Jupyter kernel for Stata. In the Stata syntax, macros are used heavily within strings. They perform text replacement and have different meanings when used inside strings.

But autocomplete is hardcoded to not apply in strings:
https://github.com/nteract/hydrogen/blob/43e8d8167eb1990da81803aa1e84015659688b4f/lib/autocomplete-provider.js#L71-L74

Would maintainers be open to the idea of a switch to allow autocompletions in string scopes in some (possibly user-defined) languages? I imagine there must be some other languages like Bash for which there are Jupyter kernels and for which autocompletion in strings might be helpful.

Alternatively, is there something I could do to the `source.stata` scope to "unscope" strings when a macro begins? It could be possible to try to take off string scopes for macros inside strings but that would be messy.

**Comment by nikitakit** [comment]
@kylebarron Thanks for bringing this up.

This would actually be useful for a number of languages. For example, it turns out that IPython can autocomplete file paths within strings! I'd be in favor of enabling it.

I'm actually not sure why it's disabled in the first place. @n-riesco do you have any idea? The git history shows you wrote the [commit](https://github.com/nteract/hydrogen/commit/29da5177c7e139ab644a64b3cb7ffb272c1358e2) that excluded strings from autocomplete.

While I'm on the topic of autocomplete, I just want to mention that hydrogen doesn't actually use the full power of Jupyter's autocomplete functionalities. The Jupyter protocols allow sending a block of text and the cursor position within that text, so autocomplete can happen anywhere in the code (see `code` and `cursor_pos` [here](https://jupyter-client.readthedocs.io/en/stable/messaging.html#completion)). Instead of relying on the kernel to do language-specific processing, hydrogen manually truncates the code it sends to the kernel and never includes anything that's *after* the cursor. If there are worries that autocompletion within strings would pick up erroneous matches, using the full protocol could help address this.

**Comment by n-riesco** [comment]
@nikitakit 

> I'm actually not sure why it's disabled in the first place. @n-riesco do you have any idea? The git history shows you wrote the commit that excluded strings from autocomplete.

I don't remember (I'm :disappointed: that didn't mention the reasons in the commit message). I'm guessing I disabled it for the same reasons it's disabled for comments: it's noisy.

As a quick fix, I'd remove `.strings` from `disableForSelector` (as not to break this functionality in the scala kernel). In the future, we could introduce more options in settings to customise how autocomplete works in Hydrogen.

> [...] Instead of relying on the kernel to do language-specific processing, hydrogen manually truncates the code it sends to the kernel and never includes anything that's after the cursor.

This predates me. @willingc, do you remember why the regexes in `lib/autocomplete-provider.coffee` were introduced?

**Comment by BenRussert** [comment]
> Is there any consensus on this? If people decided it was worth it to remove .strings from disableForSelector, that would be easy and could make it into today's (?) release.

@kylebarron I'd support this PR if you sent it over.
