### ISSUE TITLE
Matplotlib printing graph immediately (not waiting for .show())

### ISSUE THREAD

**Issue by ctr26** [nteract/hydrogen#1469]
Hi all,

My personal machine does now have this problem whereas my work machine does.
My work machine will immediately render a pyplot if I give it the line:

plt.plot(xdata, ydata)

My personal machine will wait until 

plt.show()

This means that legends and axes can't be adjusted on graphs in hydrogen nor can they be saved.

Any help welcome

Craig

**Comment by kylebarron** [comment]
In general the way I've always fixed this is by running all the plot code at once. You can do that by selecting multiple lines or using [cells](https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html#hydrogen-run-cell).

**Comment by ctr26** [comment]
Is it a bug with hydrogen or with the way the ipython environment is set up?

**Comment by kylebarron** [comment]
It's not a bug with Hydrogen in the sense that Hydrogen just sends your code to the IPython kernel, and displays the result.

You might be interested in trying out the [`hydrogen-python` extension](https://github.com/nikitakit/hydrogen-python). You can [add `plt\.` to its settings](https://github.com/nikitakit/hydrogen-python/#customisation) so that it'll automatically run all consecutive lines starting with `plt.`. That's in an extension package because it uses Python-specific syntax.

I think it might be possible to fix this from the matplotlib side by using its [object oriented interface](https://matplotlib.org/tutorials/introductory/lifecycle.html), though I haven't tried this specifically.

**Comment by ctr26** [comment]
I'm just a little confused as to why it behaves as it should on one system and differently on another. I'm guessing it's an issue with IPython?

**Comment by kylebarron** [comment]
I've never had it _not_ render immediately, so I'm not sure what to say. Did you use a magic like `%matplotlib inline` in one and not the other?

**Comment by ctr26** [comment]
As far as I recall I never did and I cannot replicate the behaviour I used to see, very confusing.

**Comment by wadethestealth** [comment]
It could have been due to differently plotly versions maybe. But are you saying this issue is gone?

**Comment by ctr26** [comment]
I'm saying that since I reinstalled anaconda I can't replicate the behaviour I used to see, I've gotten used to running multiple lines and using semicolons now though.

Thanks

Craig
