### ISSUE TITLE
Documentation of Bubbles

### ISSUE THREAD

**Issue by jkroes** [nteract/hydrogen#1474]
**Description:**

Bubbles aren't documented anywhere that I can find. After a couple hours of trying to find more information, I just figured it was something only existing users might know about.

**Comment by kylebarron** [comment]
By "bubbles" are you referring to the results, as in this gif?
![](https://cloud.githubusercontent.com/assets/13285808/20360886/7e03e524-ac03-11e6-9176-37677f226619.gif)

That's the output of commands. You can read more about there here: https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html

**Comment by jkroes** [comment]
I don't see a gif above.

I guess what I'm wondering about is how bubbles are used, and what functionality they offer above and beyond restarting a kernel and then Hydrogen: Run. When I toggle bubbles and restart-kernel-and-re-evaluate-bubbles, it seems like non-bubble code is also run.

**Comment by kylebarron** [comment]
The gif is the same as on the front page of the repository: https://github.com/nteract/hydrogen. 

I don't know what `toggle-bubbles` does. I think `restart-kernel-and-re-evaluate-bubbles` is the same as "restart and run all cells" in Jupyter.

**Comment by wadethestealth** [comment]
@kylebarron @jkroes togglebuble is for removing bubbles or preloading where you want code to be split when running a cell. Restart kernel and reevaluate bubbles divides the file into cells using only bubbles and re runs them from a fresh kernel. Bubble and results are synonymous in hydrogen, but we are working on only calling them results. However we are currently under discussion of removing these features because they don't actually work with cells like they should. See #
