### ISSUE TITLE
Q? How to find out from python library if we run Hydrogen or Jupyter notebook/JupyterLab?

### ISSUE THREAD

**Issue by kiwi0fruit** [nteract/hydrogen#1478]
How to find out from python library if we run Hydrogen or Jupyter notebook/JupyterLab?

**Comment by kylebarron** [comment]
https://stackoverflow.com/questions/5376837/how-can-i-do-an-if-run-from-ipython-test-in-python
https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook

**Comment by kiwi0fruit** [comment]
This doesn't help at all. I still cannot tell apart Hydrogen/nteract vs
Jupyter/JupyterLab.

I guess I used bad wording.

**Comment by kylebarron** [comment]
That's not possible. The [only thing you can know from Python](https://stackoverflow.com/a/39662359) is if you're in 1) Python terminal, 2) IPython Terminal, 3) Jupyter. Since there can be any frontend for Jupyter, and since there can be multiple frontends connected to the same Python kernel at the same time, it's impossible to pass that information to Python.

**Comment by kiwi0fruit** [comment]
Thanks for feedback. The only difference I found is that Hydrogen adds Atom
folder to the $PATH and nteract adds it's folder to the $PATH. When Jupyter
and Jupyter Lab do not do this. But I guess it's not very reliable...

>

**Comment by kylebarron** [comment]
Why do you want to know this?

**Comment by kiwi0fruit** [comment]
For a convenience wrapper for matplotlib dynamic plots as they are not
supported in nteract/Hydrogen. So the wrapper switched to Qt5 when on
nteract.
