### ISSUE TITLE
Support kernels in unsaved/untitled editors if grammar is set

### ISSUE THREAD

**Issue by BenRussert** [nteract/hydrogen#1532]
Back in v1, I used to love running throwaway kernels in untitled editors by `ctrl+n` then `ctrl+shift+L`to set the grammar for the kernel I wanted. We lost this functionality as a design choice when we shipped [`H20`](https://github.com/nteract/hydrogen/releases/tag/v2.0.0)

I used this almost like a "super console" for debugging/calculations/learning/tryingstuff. If I cared about what I wrote (< 10% of the time :laughing:) id save it, otherwise close without saving to get rid of the clutter.

@kylebarron and I talked about this on the hydrogen channel on the nteract slack (btw __everyone__ is welcome). I'll post below to remember and for those who missed it.

**Comment by BenRussert** [comment]
See discussions in #1008, I don't remember all the reasons we decided not to support unsaved editors, but there were some. I'll have to read this again as well.

**Comment by kylebarron** [comment]
I've been reading #1008 .

Editor ID's were turned down because they change every time the editor is closed and reopened, and we want someone to be able to close an editor and reopen it with the kernel still running. File paths allow you to do this, but don't exist before the file is saved.

It seems like a straightforward compromise is to use an Editor ID if the file is not saved, but then change the Editor ID to a path once the Editor is saved. If the Editor is closed without saving, then discard the kernel.

Thoughts?

**Comment by BenRussert** [comment]
I knew there was some issue. 

I agree in theory, but there are probably some cases to handle. For example the kernel monitor component displays a real filename. Also, the store uses a filename as the key for a file-to-kernel map. An unsaved file can eventually be saved, so we need to handle the this also.

These are some thoughts off the top of my head. It's worth doing, but may take some significant changes to implement (this is fine if you are up for it) If you want to work on this I'm glad to help.
