### ISSUE TITLE
Run markdown cells with markers

### ISSUE THREAD

**Issue by aviatesk** [nteract/hydrogen#1548]
Thanks for import/exporting ipynb notebook support with 2.8.0 release, I do love that !

And using the feature, I often write markdowns in Python/Julia scripts and found it would be nicer if we can run markdown cells with its marker specified.

I mean, currently the only way to run markdown cells seem to be like this:
![image](https://user-images.githubusercontent.com/40514306/52913626-24649200-3303-11e9-9eda-d58430e91608.png)

But it would be nicer if we can run markdown like this with a `# %% markdown` marker:
![image](https://user-images.githubusercontent.com/40514306/52913646-4b22c880-3303-11e9-8ed7-b0e236b4b2c6.png)

Any idea to support this ?
Thanks !

**Comment by kylebarron** [comment]
As it stands, your suggestion is unlikely to be implemented because it's language dependent. I.e. the `%%markdown` syntax doesn't work outside ipython.

I think something that's potentially cooler would be to somehow integrate with markdown-preview-plus to view the markdown cells with rendering in atom instead of through Jupyter

**Comment by aviatesk** [comment]
Thanks for your quick reply !

I totally got it. Certainly Hydrogen's core functionalities should be language-independent.

Close this issue.
