### ISSUE TITLE
Cell navigation: next, previous, named.

### ISSUE THREAD

**Issue by alendit** [nteract/hydrogen#1567]
It would be nice to be able to jump to previous/next cell with a single command. 

It would also help if the string after `# %%` were considered "cell's name" in appeared in the file's symbol list, but since atom doesn't seem to have a built-in notion of symbols, I think it's rather hard.

**Comment by kylebarron** [comment]
There's a command for "run cell and move down"

**Comment by alendit** [comment]
Yes, there is. But no command for 'Move Cursor Cell Up' and 'Move Cursor Cell Down', i.e. like in Jupyter where you can navigate on cell level (without executing the cells).

**Comment by BenRussert** [comment]
@alendit @mpjuers Something like this could  be done using the [atom api](https://atom.io/docs/api/latest/), then either put in your init script or into a published hydrogen plugin.

Some of the code in [code manager](https://github.com/nteract/hydrogen/blob/master/lib/code-manager.js) might give you some ideas.

Here is a quick example that will search for a python comment that you can start with.  Try this in your atom devtools console or init script:

```js
atom.commands.add("atom-text-editor", "custom:jump-back-cell", () => {
  const editor = atom.workspace.getActiveTextEditor();
  const position = editor.getCursorBufferPosition();

  editor.buffer.backwardsScanInRange(
    /^# %%/m,
    new Range([0, 0], [position.row - 1, position.column]),
    m => editor.setSelectedBufferRange(m.range)
  );
});

```

**Comment by mpjuers** [comment]
Thanks for this. I'm getting `reserved word 'const'`.

**Comment by mpjuers** [comment]
I'm having some trouble to get the above snippet to work. Basically, I get no response when I send the command from the finder or use my keymap. My apologies if this is a simple fix; I've never used JavaScript.

**Comment by hoishing** [comment]
+ 1 for this feature. Navigating between cells using keyboard shortcuts are super handy in Jupyter / Jupyerlab. Look forward to see that in Hydrogen too.

**Comment by hoishing** [comment]
following the hints from @BenRussert, just wrote a coffee script for the previous and next cell command:

```coffee
Range = require('atom').Range

atom.commands.add "atom-text-editor", "custom:prevous-cell", ->
  editor = atom.workspace.getActiveTextEditor()
  position = editor.getCursorBufferPosition()
  editor.buffer.backwardsScanInRange(
    /^# %%/m
    new Range([0, 0], [position.row - 1, position.column]),
    (m) -> editor.setCursorBufferPosition([m.range.start.row + 1, 0])
  )

atom.commands.add "atom-text-editor", "custom:next-cell", ->
  editor = atom.workspace.getActiveTextEditor()
  cursorPos = editor.getCursorBufferPosition()
  endPos = editor.buffer.getEndPosition()
  editor.buffer.scanInRange(
    /^# %%/m
    new Range(cursorPos, endPos),
    (m) ->
      cellRow = m.range.start.row
      if cellRow + 1 <= endPos.row
        editor.setCursorBufferPosition([cellRow + 1, 0])
  )
```

@mpjuers you may try putting the script in `.atom/init.coffee` and then assign keymaps for the them. Note that you got no response from the previous script because you have to import the `Range`  object from the `atom` module first.

**Comment by hoishing** [comment]
Hey guys, just created a plugin for cell navigation, moving and selection. Please check it out:

https://atom.io/packages/cell-navigation

**Comment by aviatesk** [comment]
@hoishing 
Seems cool !
Do you feel like you want to integrate these features into Hydrogen itself ?

I'm not sure whether other maintainers think about this integration, but I personally happy if we can use those features inside of Hydrogen.

/cc @BenRussert @kylebarron

**Comment by hoishing** [comment]
My original idea was to use these features with Hydrogen, but later I found that Jupytext is another use case. Thats why I made it as a separate plugin.

Of course I would like to see it integrated into Hydrogen, but not sure what is the proper way of doing so. Say shall we just make it as a dependency instead of putting it into Hydrogen code base? Because cell navigation / moving is indeed pure text manipulation, which has no interaction with the jupyter kernel at all.

**Comment by aviatesk** [comment]
@hoishing

> but later I found that Jupytext is another use case. Thats why I made it as a separate plugin.

Understand. So is there maybe another plugin for Jupytext that may want to use these features ?
If you think you almost always use Hydrogen when you edit Jupytext (like connecting to the Jupyter kernel and check the result in Atom), then the integration might be better idea.

For integration, I'm not sure adding as a dependency is the best way.
Hydrogen codebase has utilities like detecting cell deliminator for different grammars and so, and if you find them useful too to enhance your features, then migrating your code into Hydrogen would be better choice.



Possible drawbacks of migrating your code into Hydrogen would be, you have to _activate_ Hydrogen first even when you just want to use those features. This is because Hydrogen delays its activation for better starting up, and that's why the first Hydrogen command takes seconds.
Thus even if you just want to use these cell manitpulations, you need to activate other Hydrogen features, and you may find this  annoying.

**Comment by hoishing** [comment]
@aviatesk sorry for the late reply.
As you said, simple cell manipulation need to activation Hydrogen after migrating it into Hydrogen. Its a bit annoying... I prefer just keep it as a separate plugin at the moment.

**Comment by aviatesk** [comment]
@hoishing 
Okay !
You can add your plugin to this section if you want :)
https://github.com/nteract/hydrogen#plugins-for-hydrogen

**Comment by hoishing** [comment]
@aviatesk 
just opened a PR for updating the README plugin section, please take a look :)

**Comment by BenRussert** [comment]
Really cool package @hoishing! I love that it works for more than just hydrogen too!

I'll close the issue and refer anyone else to https://atom.io/packages/cell-navigation
