### ISSUE TITLE
Export Notebook has disappeared from the command palette

### ISSUE THREAD

**Issue by sschuldenzucker** [nteract/hydrogen#1635]
Seriously. This is what just happened to me. I was happily coding when "Hydrogen: Export Notebook" suddenly wasn't available in the menu any more. I had definitely used it in the same session. Restarting did not help. 

The problem occurred when I was editing Julia and modifying (in fact, newly creating) my `snippets.cson` file. But I can't export from python, either.

No idea how I would reproduce this. Can anyone help me track down this issue?

**Versions:**

Windows 10, Hydrogen 2.9.0, Atom 1.37.0

**Plugins:**

Do you have any Hydrogen plugins installed and active?
- [ ] hydrogen-python
- [X] Hydrogen Launcher
- [ ] Data Explorer

**Logs:**

Console with Hydrogen debug output activated didn't show anything suspicious.

**Comment by wadethestealth** [comment]
@sschuldenzucker assuming you mean the `ctrl-Shift-p` menu from atom, did you have any other Hydrogen command available. If not, the package may not have been activated. The export command is added immediately once the package is activated and doesnt not remove until the package is deactivated.

**Comment by sschuldenzucker** [comment]
Yes, the other commands are there, e.g., Import Notebook works just fine.
What's even weirder: when I renamed my `.atom` directory for a fresh start
and reinstalled only hydrogen, the problem persisted. Does the export
function depend on any external files maybe?

**Comment by wadethestealth** [comment]
@sschuldenzucker Yes it relies on export-notebook.js in the hydrogen/lib folder, but the command does gets added at the same time as all the other functions

**Comment by hoishing** [comment]
I experienced the same problem, all hydrogen commands exist except export notebook... the export-notebook.js file is intact. I finally re-install the Hydrogen package and the export command come back.

**Comment by wadethestealth** [comment]
@sschuldenzucker @hoishing The export-notebook.js file also requires 4 modules. 2 are npm (fs and path) The other two are listed below.
```
const { dialog } = require("electron").remote;
const { stringifyNotebook } = require("@nteract/commutable");
```
The commutable module should be installed with hydrogen and the electron module is what atom is built on top of.
You could trying running those 2 lines in the dev tools of atom, and seeing if any errors are produced while Hydrogen is active and you can see the other commands.

**Comment by sschuldenzucker** [comment]
Aha! "So that's why you call it a baked potato!," as we say in German. The electron line goes through, but the `@nteract/commutable` one does not. I get (modified the line to be able to run it several times):

```
> thestringifyNotebook = require("@nteract/commutable");
module.js:545 Uncaught Error: Cannot find module '@nteract/commutable'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (C:\Users\steff\AppData\Local\atom\app-1.37.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\steff\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:11:154765)
    at Module.require (file:///C:/Users/steff/AppData/Local/atom/app-1.37.0/resources/app.asar/static/index.js:40:43)
    at require (internal/module.js:11:18)
    at <anonymous>:1:24
```

The `commutable` package sits at:

    C:\Users\steff\.atom\packages\Hydrogen\node_modules\@nteract\commutable

together with the following other packages below `...\@nteract\`
```
commutable/    markdown/  plotly/            transforms/      transform-vega/
display-area/  mathjax/   transform-plotly/  transform-vdom/  vega-embed-v2/
```

Turns out I cannot load *any* of them using the method above.

Could this be a file naming issue on Windows?

NB: In contrast to @hoishing, re-installing did not help for me.

**Comment by aviatesk** [comment]
@wadethestealth @sschuldenzucker 
If you call `require("@nteract/commutable")` from the dev console, you're supposed to be unable to import it, because the npm is not there under the default console scope.
`require("electron")` works just because Atom itself _requires_ it.

**Comment by aviatesk** [comment]
I doubt this issue is because of import/require stuff, because if an Atom package can't load its dependency module, the error notification is shown and the package itself can't be activated.

And I found that the commands defined after the `Hydrogen:Export-Notebook` (like `Hydrogen:Fold-Current-Cell`) are also sometimes disappear.
Thus our `store` seems to dispose its subscriptions _partially_, which still sounds really weird.

/cc @BenRussert You have any idea to this ??

**Comment by sschuldenzucker** [comment]
@aviatesk True, I can confirm that these commands (at least `Hydrogen:Fold-Current-Cell`) are also gone for me.

**Comment by wadethestealth** [comment]
@sschuldenzucker could you try running the `Hydrogen:Start-Local-Kernel` command if you already have a kernel running than `ctrl-shift-f5` and run then

**Comment by wadethestealth** [comment]
@aviatesk There is no way for store to partially dispose itself. There is only one function that disposes the whole store subscriptions. My guess is the package is not actually activated, and therefore only displays activation commands but no other commands.

**Comment by wadethestealth** [comment]
@sschuldenzucker Can you confirm you still have these issues after the steps I gave above?

**Comment by sschuldenzucker** [comment]
@wadethestealth Sorry for the delay. Yes, this does its thing! `Hydrogen:Start Local Kernel` makes the lost commands reappear, including `Export Notebook` and `Fold Current Cell`.

**Comment by wadethestealth** [comment]
@sschuldenzucker You don't have any problems with your hydrogen then. When you want to use hydrogen you must use one of the availabile commands first. These are called activation commands, and they start the hydrogen package and enable all other commands

**Comment by sschuldenzucker** [comment]
@wadethestealth Ah, I see! Thanks a lot for resolving my issue, and so quickly!

Having said that, the fact that these "activation commands" exist was not obvious to me. You might want to make this clearer to the user. I'm sure there are reasons why you implemented it like this and I'm sure it's in the documentation somewhere, but from a mere user perspective I just didn't expect that you'd need a running kernel to export as a notebook or even do a very editor kind of thing like cell folding. Perhaps you want to make the commands available, but raise an error if there's no kernel? Just a thought.

**Comment by aviatesk** [comment]
@sschuldenzucker 
Good thought.
I think it's more reasonable to add `hydrogen:import-notebook` and `hydrogen:export-notebook` as activation commands.
Your thought ? @wadethestealth

**Comment by aviatesk** [comment]
I also wonder why you didn't register the commands as activation ones when you implemented those features. Is there any reason ?
cc/ @kylebarron

**Comment by wadethestealth** [comment]
@aviatesk I am not too sure what justifies an activation command and how many we are allowed. What I know is that the activation commands are meant to save atom time while booting

If we don't decide to make these activation commands this should be addressed in the documentation.

**Comment by aviatesk** [comment]
@wadethestealth 
AFAIU activation commands are there just because they allow an user to speed up package-loading time by delaying package-loading until one of these activation commands is invoked (i.e.: when an user don't use Hydrogen while using Atom, s/he can ignore Hydrogen's loading time at all).
Thus activation commands are those can be used as the very _first-time_ command when an user start to use Hydrogen features.

I suspect @kylebarron only exported `hydrogen:import-notebook` since an usual Hydrogen workflow with the command would be like:
1. import .ipynb file as, say, .py file: `hydrogen:import-notebook`
2. edit the .py file using interactive features of Hydrogen
3. finally export again the file as .ipynb notebook: `hydrogen:export-notebook`

In this workflow, `hydrogen:import-notebook` is better to be registered as an activation command, since it's used as the _first-time_ command.

But atst I think those import/export notebook features are so useful that I suspect some users may want to use the `export-notebook` command as the _first-time_ command, for example, when they only want to use the command.
In this case, an user should invoke one of current activation commands (like `hydrogen:start-local-kernel`) first to use `export-notebook`, which seems inconvenient.

And IMO we can say the cost of registering `export-notebook` command as an activation one is nothing because it's currently not bind to any keybindings by default, and thus it's very rare that an user accidentally invokes this command and have to wait for undesired Hydrogen loading time.

**Comment by wadethestealth** [comment]
@aviatesk go ahead and submit a pr ask for review and I'll sign off on it.
