### ISSUE TITLE
Downloaded files from plotly saved to nowhere

### ISSUE THREAD

**Issue by kyle-sama** [nteract/hydrogen#1653]
When creating a plot using plotly:

```
from plotly import offline
offline.init_notebook_mode()

offline.iplot([{"y": [1, 2, 1]}])
```

When clicking the "Download plot as png" button:

![Screenshot from 2019-06-05 15-54-54](https://user-images.githubusercontent.com/2487114/58936433-b2796100-87aa-11e9-846c-b9105a63036a.png)

The messages
"Taking Snapshot - this may take a few seconds"
"Snapshot succeeded - newplot.png"
are displayed:

![Screenshot from 2019-06-05 15-50-45](https://user-images.githubusercontent.com/2487114/58936473-c9b84e80-87aa-11e9-9d52-501ca8577aaf.png)

but this newplot.png file does not exist. In Jupyter this would cause your browser to download the image, but in Atom, it seems like it doesn't do anything...

**Comment by wadethestealth** [comment]
Can reproduce. I am trying to investigate which script runs to figure out where its failing.

**Comment by wadethestealth** [comment]
The issue is that clicking links inside atom do nothing. Plotly essentially creates a download link off page and clicks it. This doesn't work in atom for some reason. the fix would involve editting plotly.
To correctly download the code looks something like this
```
const electron = require('electron');
electron.remote.getCurrentWebContents().downloadURL(insertCreatedUrlFromPlotly);
```
This code then opens a window for you to save the file and defaults to the downloads folder with the file named download.png.

@BenRussert How should I fix this issue without editting plotly.js directly? Can I edit @nteract/transforms to include an option for electron or does this seem unlikely?

**Comment by BenRussert** [comment]
No idea @wadethestealth. It sounds internal to plotly.js, but if you figure out the problem you may be able to PR there and fix.

**Comment by wadethestealth** [comment]
@BenRussert there is no likely solution for plotly to implement, since it won't be able to detect electron vs chrome, but there are 2 ways to restore how it works just for hydrogen. One is I make a package that listens for link clicks with a download tag and are base64 imgs, or I use the div reference in @nteract/transform-plotly to modify the function calls and returns of that link. However, I dont know if @nteract/transform-plotly wants me to put in code for electron only?

**Comment by BenRussert** [comment]
Transform plotly should work in both web and electron environment. Have you tried this same bug in the nteract desktop app? I wonder if a fix is there or if the issue is atom specific?

**Comment by wadethestealth** [comment]
@BenRussert its atom specific because it doesn't handle links that aren't http or https. I also browsed the packages and no one else has implemented a link opener for base 64 data img links
