### ISSUE TITLE
Add config setting to revert to pre-2.10.0 output soft-wrapping behaviour

### ISSUE THREAD

**Issue by matthewgdv** [nteract/hydrogen#1679]
**Description:**

Ever since the latest update (2.10.0) the inline output in python is being soft-wrapped in most cases, where earlier it would just provide a horizontal scroll-bar.

For example, when looking at the repr() of a list too large to be shown on a single line, atom will always put each element of the list in its own line. However, if any given element is longer than the available space in the output bubble, it will now be split across multiple lines, whereas before this last version each element would remain on its own line, and you'd just have to scroll right.

Here's a screenshot showing an example of what I mean:

![image](https://user-images.githubusercontent.com/37582022/60165030-8162de00-97f6-11e9-9e16-b4bd4016cbe1.png)

However, when you ctrl+click to open it in a new pane, you see the repr() as it actually is, without the soft wrapping:

![image](https://user-images.githubusercontent.com/37582022/60165123-ae16f580-97f6-11e9-8840-01bcabae904d.png)

This is how it used to show in the output pane before.

Is there any way to recover the old functionality? If there isn't currently an option to do so, would it be possible to have a setting implemented for the next release to completely disable this new kind of soft-wrapping in the inline output panes?

I've found this: https://github.com/nteract/hydrogen/issues/1569, which looks like the issue that caused this change. Someone specifically stated: 'I think this is a fix that most people want, so a config probably isn't needed. If people want they can always set their personal atom stylesheet.'

However, I disagree. I much prefer the old functionality over the new one and I'm sure I'm not alone. Could we please get a config setting to toggle this behaviour?

In the meantime, could someone explain to me how I can revert this change just for myself using a stylesheet? I've never used any of that stuff, so I'm not sure how I'd go about doing that. I'd be so grateful.

**Versions:**

Windows 10 Professional
Atom: 1.38.2
Electron: 2.0.18
Chrome: 61.0.3163.1000
Node: 8.9.3

**Plugins:**

- [x] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

**Comment by aviatesk** [comment]
Hi, I just modified the behaviour in the latest release.
If you want to revert this, put this snippet into your stylesheet.

> ~/.atom/styles.less

```
.hydrogen {
  code, pre {
    white-space: pre;
  }
}
```

Cheers,

**Comment by wadethestealth** [comment]
@aviatesk Do you think this should be a checkbox/config in the package settings? Or, the original issue was only with the output area, so do you want to revert your commit to only apply to the output area by putting in in `resultview`. That would be the closest to original functionality while still fixing the bug.

**Comment by aviatesk** [comment]
@wadethestealth 
IMO it sounds more friendly, but we concluded there wound no strong need for that when I crafted the PR.
@BenRussert what do you now think about this ?
I'm okay with either way.

**Comment by aviatesk** [comment]
Moving only into `resultView` is better in any case btw.

**Comment by shr00mie** [comment]
is resultView the dedicated output pane vs inline output? if that's what this was designed to fix (wrapping in dedicated hydrogen output pane to the right), that would make sense due to the limited horizontal real estate. i think most inline folks were totally content with how inline output was functioning under 2.9.0.

and please pardon the ignorance, but is it not possible to link wrap functionality under inline/dedicated output for Hydrogen per the below from the package configuration settings? while i suspect that they pertain to soft wrapping the actual code being typed instead of output, but if someone likes wrapping that much, that might be a good general setting for that, or possibly add additional UI configuration elements for output wrapping in both inline and dedicated as well?

![image](https://user-images.githubusercontent.com/7096317/60202985-93497e80-9800-11e9-8330-a3159dfc57d2.png)

**Comment by wadethestealth** [comment]
The resultview is a block that is displayed both inline and in the output area. The only difference is how it gets shown. We already have separate css for the output area version and the inline version and I was suggesting he add to it instead of to the stylesheet, which would fix the bug but maintain previous inline behavior @shr00mie

**Comment by BenRussert** [comment]
> what do you now think about this ?
I'm okay with either way.

@aviatesk I'm ok either way too. 

My original thought was that the built in stylesheet `styles.less` is the highest priority stylesheet, so a user can customize anything that way. If people prefer to check a box, we could go the config route too.

**Comment by aviatesk** [comment]
> My original thought was that the built in stylesheet styles.less is the highest priority stylesheet, so a user can customize anything that way.

I see, and very agree with you on this.
As UI components in Atom, the stylesheet is everything and it would be more Atom-way to tweak that. Thus I think creating an example  about this "wrapping" customization tweak in [this section](https://nteract.gitbooks.io/hydrogen/docs/StyleCustomization.html#multiline-result-view) in our style customization section would be better and friendly.

@wadethestealth What do you think ?

@BenRussert 
And I wonder why you create a config of `Output are fontsize` even tho we can tweak it via stylesheet if it's not hard-coded.

**Comment by wadethestealth** [comment]
While I think stylesheets are the best way to customize, I also believe that commonly changed values should be configurable in package settings. Also this allows for a copy of a config file rather than a stylesheet in which may differ because of packages between two machines. Also @aviatesk I find it really useful to go to the file where the change was made look at the git blame and then see what PR a commit came from, and there is generally a reason in the PR or an issue linked. I think it helps see what were the problems of the past and what did they do to solve them.

**Comment by aviatesk** [comment]
> Also @aviatesk I find it really useful to go to the file where the change was made look at the git blame and then see what PR a commit came from, and there is generally a reason in the PR or an issue linked. I think it helps see what were the problems of the past and what did they do to solve them.

Yeah, definitely 😅 Thanks for pointing that out.
I jumped and saw the original issue, and AFAIU there seemed to be no discussion about encouraging an user to tweak stylesheet.

> also believe that commonly changed values should be configurable in package settings

Yeah, we can add descriptions for configs and thus an user don't need to jump to our documentation for what the config is supposed to do. But once we set a config value for something about UI, an user can't change it via stylesheet.
For example, as for this wrapping things, if we offer two choices like `pre-wrap` or `pre`, we can't no longer choose like `normal` (stripping the whitespace at head of line) since it's now hard-coded.
I think this such a very tiny difference tho.

> Also this allows for a copy of a config file rather than a stylesheet in which may differ because of packages between two machines.

As for this I wonder we can share styles.less as well as config.cson between machines like using GitHub, thus might not be better or less.

**Comment by wadethestealth** [comment]
Is there not a way for the config to edit the stylesheet that way it is still overwritable?

**Comment by aviatesk** [comment]
I've been unable to find a solid description about the priority of inline-style vs. css-style, maybe because inline-style's officially not recommended and thus we're not supposed to do this kind of tricky things.

And I personally don't prefer inline-style if not necessary...

**Comment by wadethestealth** [comment]
Not sure what you mean by inline, but if a style is being applied directly to an element in it's html style attribute it is always more specific. It is important to know how css cascades as that decides priority.

**Comment by aviatesk** [comment]
For "inline-style" plz refer to https://zhenyong.github.io/react/tips/inline-styles.html.

And by "priority" I meant when both inline-style and stylesheet style _collide_ on the same class object.

**Comment by wadethestealth** [comment]
Ok inline styles can't collide with stylesheets ever because they are more specific. Inline styles are the most specific type of style. Styles only collide when they are of the same specification, in which the most recent value is always chosen.

**Comment by aviatesk** [comment]
Nope, it does collide.
For example, try to tweak font-size of output view via stylesheet.
It wouldn't take any effect because the inline-style takes the priority and this is what we're talking about so far.

**Comment by wadethestealth** [comment]
@aviatesk could we try something like this
http://lesscss.org/usage/#using-less-in-the-browser-modify-variables

**Comment by wadethestealth** [comment]
@aviatesk I have a perfect solution. Just add that to a class and add the other option to a second class then swap classes on the check box. This way there is never an inline style.

**Comment by aviatesk** [comment]
Umm interesting.
But do you mean adding the same classname to the those swapped components ?
If not, there would be an inline style and it sounds rather complicated to me.

For example, an user can make styling tweaks on one of those components and if s/he changed the config value, the tweaks would appear like disappeared and such a thing would be annoying...

Rather I feel like taking the simpler choice: stylesheet or config (sorry for taking back the discussion)

**Comment by wadethestealth** [comment]
I think use the config, but all the config does is change the class name instead of the style directly. So then you just make two class one pre and one prewrap. Since elements can also have unlimited classes it won't affect other styles

**Comment by wadethestealth** [comment]
It would also still allow for stylesheet override. I could take it over if you would like

**Comment by aviatesk** [comment]
So you mean the class name of the component that should be tweaked by an user's stylesheet doesn't change even when the config changes ?

**Comment by wadethestealth** [comment]
Correct. Stylesheet has two classes and never changes. Component class name changes for just that one rule.

**Comment by wadethestealth** [comment]
The above comments have been hidden because I went a different route with the solution to minimize the number of code lines.
