### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by yinzhema** [nteract/hydrogen#1774]
### Description

I downloaded the hydrogen package in Atom, and ran into `Cannot find module '@nteract/presentational-components'`, so I just followed the issue report to `Missing @nteract/presentational-components on fresh install (#1768)`. When I tried to run this command: cd .atom/pacakges/Hydrogen && app install, terminal gives me the following error message:
<img width="554" alt="Screen Shot 2019-09-17 at 11 15 54 AM" src="https://user-images.githubusercontent.com/31641047/65055982-1d0b7280-d93e-11e9-9103-b3916980388f.png">

###Versions
Atom: 1.40.1
Hydrogen: 2.12.0
OS: 10.14.6

**Comment by wadethestealth** [comment]
Can you please post your atom versions as well as your os and version?
I believe the fix will be to download python 2 and point your python path to that and then run install

**Comment by yinzhema** [comment]
> Can you please post your atom versions as well as your os and version?
> I believe the fix will be to download python 2 and point your python path to that and then run install

I just posted my atom, hydrogen, and os versions. Thanks!

**Comment by wadethestealth** [comment]
Are you on windows? If so download python 2 and edit your Python env var to be the path of the python 2 and then install.

**Comment by phromo** [comment]
your atom installation (specifically apm, the package manager) is broken.
if you run `apm --version` it probably throws the same error, right?

If you don't care about your broken atom, try the alternate workaround, chances are u have a working nodejs in your path
```
cd ~/.atom/packages/Hydrogen
npm install --save  @nteract/presentational-components@^3.0.6
```

Otherwise, reinstall atom according to the installation instructions

**Comment by wadethestealth** [comment]
@phromo is probably correct

**Comment by yinzhema** [comment]
I tried to re-install atom a couple of times, but it would still give me
the same error. And when I tried to run npm install --save
@nteract/presentational-components@^3.0.6, it gives me a npm command not
command

**Comment by wadethestealth** [comment]
npm is not a command because you don't have node or npm installed. You could install this yourself and continue with his fix, or you could try to use my solution downloading python 2. However I am curious if you are able to install any packages not just hydrogen. If you cant then I would open an issue over in atom or apm

**Comment by yinzhema** [comment]
Worked fine now. Thanks a lot!!!

**Comment by wadethestealth** [comment]
Please explain what you did so that anyone else who comes across this issue will know what to do

**Comment by yinzhema** [comment]
> Please explain what you did so that anyone else who comes across this issue will know what to do

I downloaded npm here: https://nodejs.org/en/,
then ran `npm install --save @nteract/presentational-components@^3.0.6` on terminal.
Hope this helps
