### ISSUE TITLE
Have problem run on Mac 

### ISSUE THREAD

**Issue by IronChen93** [nteract/hydrogen#1794]
Hi everyone, I had a problem on running hydrogen on Mac OS. 
<img width="462" alt="Screen Shot 2019-10-14 at 23 56 14" src="https://user-images.githubusercontent.com/34754551/66799982-599ca080-eee1-11e9-9c77-ba10a3ac71d6.png">

I think the problem is the python 3 path isn't set right, and python 2.7 is the default.
Does anyone can help me to solve it? 

Thank you.

**Comment by wadethestealth** [comment]
Yes you are correct. you python path is set to python 2. set your python path to python 3 or modify your kernel to use the correct python. See https://github.com/jupyter/notebook/issues/2563 for some help. However this is not a hydrogen issue, but an incorrect install. We recommend opening an issue over on your kernel's repo for support. Other community member are free to comment here to help out though.

Closing because this is not a hydrogen issue.
