### ISSUE TITLE
No kernal for language python found

### ISSUE THREAD

**Issue by Underbite-productions** [nteract/hydrogen#201]
Great work creating a more interactive environment for atom, but alas for me I cannot get it to work ...

I think this maybe something to do with setting correct kernal path, but I cannot find kernal.json file use as a reference in the settings.

When I go run a line of python code (cmd+shift+P hydrogen: run), this is the error i get (see screen shot attached):

No kernal for language python found
Check that the language for this file is set in Atom and that have a Jupyter kernal installed for it.

I have plenty of kernals installed on my machine as i typically use virtual environment and I also have the anaconda distrubution installed as well.
![screen shot 2016-03-16 at 9 07 05 am](https://cloud.githubusercontent.com/assets/13551065/13797488/15bff8c0-eb62-11e5-809a-43c8399b37da.png)

**Comment by lgeiger** [comment]
If your editor grammar is set to `MagicPython` instead of `Python`, hydrogen is searching for a kernel named `magicpython` rather than `python`. You can check this setting at the lower right corner of Atom.

Either change the grammar of your editor to `Python` or if you like to keep the syntax highlighting of MagicPython add `{"MagicPython": "python"}` to `Language Mappings` in the Hydrogen settings.

**Comment by slavaGanzin** [comment]
@lgeiger Are sure? I have opposite key/values:
```{"babel":"Babel ES6 Javascript", "babel":"Javascript with jsx"}```

**Comment by m-guggenmos** [comment]
@lgeiger This isn't working for me, I keep getting the `No kernel for language magicpython found` error.

**Comment by lgeiger** [comment]
I reproduced this issue.

If you add `{"python": "magicpython"}` to your language mappings everything should work fine.

This setting is usually used to map a kernel language name to atom's grammar name. Since MagicPython changes atom's grammar name this setting has to be applied the other way round.

You can also use the kernel mapping setting instead. Just add `{"magicpython": "Python 2"}` there.

**Comment by m-guggenmos** [comment]
Great, I can confirm that exchanging the two names works.

**Comment by lgeiger** [comment]
Awesome! 🎉

**Comment by mjamilrahman** [comment]
[ Problem solved ] " no kernel for python language found"

I am using Linux Operating System ubuntu 16:04
Atom 1.7.4

Open your beloved Terminal <3

$ sudo apt autoremove ipython
$ sudo apt install python-pip -y
$ pip install --upgrade pip

then, install ipython[notebook]

$ sudo pip install ipython[notebook]

Done
