### ISSUE TITLE
error notifications don't show up

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#209]
Since #202 the error notifications disappeared for me.

I'm talking about these notifications:
<img width="487" alt="bildschirmfoto 2016-03-18 um 20 49 42" src="https://cloud.githubusercontent.com/assets/13285808/13890401/8c71008c-ed4b-11e5-84ec-bd7ad3d74c39.png">

**Comment by n-riesco** [comment]
Actually, I removed this on purpose because I thought it duplicated the information already shown in the result bubble.

I'm OK to bring it back if you find it useful.

**Comment by lgeiger** [comment]
You don't have to bring it back for me. I just noticed it and thought some error prevents it from being displayed.

The error in the result bubble is enough.

**Comment by n-riesco** [comment]
@slavaGanzin Do you need this notifications back? If not, let's close this issue.

**Comment by slavaGanzin** [comment]
@n-riesco It works better for julia kernel - shows info and debug messages. In python it seems not so usefull, but as you can see not everything arrives to result bubble:
![screen](https://cloud.githubusercontent.com/assets/1011721/13905073/ea90bdb0-eebd-11e5-9ad7-abb07f95c03b.png)

Before I thought to change behavior - hide error messages, display X in result bubble and show atom errors - it show glorified stacktrace.

So yes I need that, but improvements needed too

**Comment by slavaGanzin** [comment]
Looks like it bubble responses ignores some errors. This is OK while CUDA erorr isn't critical, but user should be notified about fallback to CPU. 
![screen](https://cloud.githubusercontent.com/assets/1011721/13905128/2f673e4a-eebf-11e5-8ac3-ee0d11fb582f.png)

**Comment by n-riesco** [comment]
@slavaGanzin I think those messages are actually invisible to Python. I've seen this happening with python modules that wrap FORTRAN or C/C++ libraries that use `stdio` to report warnings and errors. I imagine the python module doesn't wrap the `stdio` use by the underlying library.

There are a few arguments for not showing them:
- the kernel uses `stdout` and `stderr` for a different purpose; namely, to display log messages (which can be very verbose)
- currently, the Jupyter notebook doesn't show them (I guess that, like python, Jupyter doesn't see them).
- in principle, the `stdio` associated with a kernel session and the `stdio` of the script that starts a kernel session may not be the same. The frontend (in this case Hydrogen) sees the `stdio` of the kernel session, only because the session is run in the same process that the script that started the kernel session. Hydrogen wouldn't be able to see the `stdio` of the kernel session, if the session was remote.
- the only way specified in the Jupyter Messaging Protocol to publish data written in the kernel `stdio` is a `stream` IO message.

**Comment by slavaGanzin** [comment]
@n-riesco I think stdout notify can be removed, but not stderr one: https://github.com/nteract/hydrogen/blob/master/lib/kernel.coffee#L71

**Comment by n-riesco** [comment]
@slavaGanzin What about the 4 points I made in my previous message?

**Comment by slavaGanzin** [comment]
> There are a few arguments for not showing them
I can't get what are you talking about. All this messages are visible in iPython. If you are talking about topic starter a-like messages, I think they can be removed.

But if some library want to notify me that it works not as expected - in my case it was CUDA-tensorflow interaction I want to see that. Without trying to catch an error in my developer console.

You can review this: https://github.com/nteract/hydrogen/issues/109
That error was shown in repl, but not in hydrogen.

When we merged PR i thought, it would be ideal to have a slider that change level of verbosity, but now I think it's excessive decision.

**Comment by n-riesco** [comment]
Those messages are invisible to IPython. IPython doesn't see them. Python doesn't see them. You won't be able to write a Python script that manipulates them, unless you capture the stdio of the process that runs the Python interpreter.

Since this it's important too you, I will implement a setting to enable/disable this kind of notifications.

**Comment by n-riesco** [comment]
#218

**Comment by slavaGanzin** [comment]
> iPython doesn't see them.

```
 ipython2
Python 2.7.11 (default, Mar  3 2016, 11:00:04) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally

```

**Comment by n-riesco** [comment]
Yeah right! And now storet them into a variable and do something with them.

**Comment by n-riesco** [comment]
or try with this kernel spec:

```
        "ipython2": {
            "spec": {
                "display_name": "IPython 2",
                "env": {},
                "argv": [
                    "ipython",
                    "kernel",
                    "-f",
                    "{connection_file}", ">& /dev/null"
                ],
                "language": "python"
            }
        },
```

**Comment by slavaGanzin** [comment]
How I can store stdout of native library into variable?

**Comment by n-riesco** [comment]
That's the point I'm trying to make. Unless you capture the process stdout, you can't. Libraries shouldn't report error messages like that, because programs using those libraries won't be able to act on those messages.

**Comment by rgbkrk** [comment]
Even better case to try out is two Jupyter consoles connected to the same kernel.

**Comment by slavaGanzin** [comment]
I admire that you know how libraries should work and where they should report their problems. So you decide to delivery every library maintainer a new paradigm how they should do their work?

Error is an error, and you can filter it because of paradigm shift. Kernels write to stdout, stderr ,they shouldn't, but they do.

**Comment by n-riesco** [comment]
@slavaGanzin It isn't a new paradigm. Please, try to understand what I said before:
- The Jupyter messaging protocol only defines `stream` IO messages for this purpose.
- Hydrogen uses kernel specs to launch a kernel. The kernel spec specifies a command to launch a kernel. This launching command and the kernel may not be the same thing.
- Also note that in your example the kernel doesn't write to `stdout` and `stderr`, but rather it invokes a library that writes to `stdout` and `stderr`.

**Comment by rgbkrk** [comment]
> Also note that in your example the kernel doesn't write to stdout and stderr, but rather it invokes a library that writes to stdout and stderr _yet not on `stream` IO messages_

**Comment by slavaGanzin** [comment]
Do what you want

**Comment by n-riesco** [comment]
@rgbkrk Let me be more precise with the wording: it invokes a library that it isn't written in Python (C++ in this case) and that library writes to the process `stderr` instead of  writing to Python's `sys.stderr`.

**Comment by rgbkrk** [comment]
Ahhhhh! I gotcha now! Yup I was definitely confused there. They're not re-piping stderr from child processes, hence it doesn't show up in the notebook.

**Comment by n-riesco** [comment]
@rgbkrk Actually, I picture it a little different (no need for child processes):
- the OS provides each process with standard streams (in Linux, this is `/proc/<PID>/fd/0`, `/proc/<PID>/fd/1` and `/proc/<PID>/fd/2`).
- the Python interpreter runs in a process, and thus has its own `/proc/<PID>/fd/0`, `/proc/<PID>/fd/1` and `/proc/<PID>/fd/2`.
- Python scripts run by the Python interpreter usually access the standard streams through `sys.stdin`, `sys.stdout` and `sys.stderr`.
- The issue discussed here arises when `sys.stdin`, `sys.stdout` and `sys.stderr` are by-passed, and  `/proc/<PID>/fd/0`, `/proc/<PID>/fd/1` and `/proc/<PID>/fd/2` are accessed directly.

You can see this issue at action by running the following script in the console and in the notebook:

```python
import os
os.system("echo Hi! > /proc/$$/fd/1")
```
