### ISSUE TITLE
export notebook not working (does not produce a file)

### ISSUE THREAD

**Issue by lucasfigueiredo** [nteract/hydrogen#2094]
macOS Catalina 10.15.7
Atom 1.56.0 x64
Hydrogen 2.15.3
Custom configurations: disable auto-import, directory to start the kernel in > current directory of the file

Either from the menu or from the cmd+shift+P, the option "export notebook" shows the file dialog but does not produce a exported file even though it does not show any errors

(note: one or two updates ago, it was working properly. I tried to reinstall but the issue persisted)

**Comment by BigMcLargeHuge** [comment]
Same here
Ubuntu 20.04
Atom 1.56.0 x64

**Comment by BigMcLargeHuge** [comment]
@lucasfigueiredo I reverted to Hydrogen 2.14.7 and the problem seems to still be there

**Comment by matrix-ranger** [comment]
Same here
macOS Big Sur 11.3.1
Atom 1.56.0 x64
Hydrogen 2.15.3

**Comment by kuri54** [comment]
Same here
macOS Big Sur 11.2.3
Atom 1.56.0 x64
Hydrogen 2.15.3

**Comment by aminya** [comment]
This is fixed in the latest version.

**Comment by kuri54** [comment]
Thanks for the update!
I have confirmed that I can export successfully.

However, there seems to be a problem with the remote connection.

`Forbidden`
`403 GET・・・・・ referer=None`
I can't connect remotely because I get the message

I haven't changed anything except for updating and exporting .ipynb as a test.
