### ISSUE TITLE
Figure Size

### ISSUE THREAD

**Issue by ywhuofu** [nteract/hydrogen#250]
Thanks for the awesome package! 

Would it be possible to make the figure size adjustable? I've tried to adjust it using matplotlib, but didn't seem work.

**Comment by lgeiger** [comment]
Adjusting the figure size in `matplotlib` is done using `plt.figure(figsize=(w, h))`. Though if the figure is to big it will be scaled down to fit (https://github.com/nteract/hydrogen/issues/240).

Please try if works for you:
```
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

t = np.linspace(0, 10, 500)
s = np.sin(t)

plt.figure(figsize=(8, 6))
plt.plot(t, s)
plt.show()
```

**Comment by n-riesco** [comment]
@ywhuofu I'm closing this issue. Please, feel free to reopen it if you need more help.

**Comment by pierregodard** [comment]
does it work for you the same way if you add `%config InlineBackend.figure_format = 'retina'` after `%matplotlib inline`? If i do, `plt.figure(figsize=(a, b))` is not taken into account anymore on my end. It produces a higher resolution figure, but seems to also force a larger size. I don't experience this on a regular ipython notebook. Maybe it's a `matplotlib` backend configuration problem but i'm not well versed in that.

[just saw the STDIN support update  🎉, you guys are doing much awesomeness! thank you!]

**Comment by n-riesco** [comment]
TODO

- [ ] Test `%config InlineBackend.figure_format = 'retina'`

**Comment by pierregodard** [comment]
@n-riesco sorry for raising this, it was a misunderstanding on my end. I was executing something like:
```
plt.figure(figsize=(15, 4))
plt.hist(samples, bins=40)
``` 
line by line (with `run-and-move-down`) and i think the address of the figure produced by the first line gets lost and a second figure is created by the second line (i use `%matplotlib inline` which is maybe changing the behavior since i don't call `plt.show()`). If i execute the code as a block, the figure is resized properly!

[i also now use `%config InlineBackend.figure_format = 'svg'` instead of `%config InlineBackend.figure_format = 'retina'` but i don't think it matters much here.]

thank you again for your help and the magic of `hydrogen` :-))

**Comment by masonlr** [comment]
@lgeiger, changing between these two `InlineBackend` options is doubling the displayed figure size for me:

```python
%config InlineBackend.figure_format = "png"
%config InlineBackend.figure_format = "retina"
```

Do you know of any workaround or code that I can add to `styles.less` in order to allow me to use the retina option without changing the displayed figure size?

![demo](https://cloud.githubusercontent.com/assets/5828176/26451728/2dd5eab0-4155-11e7-937c-f28995d18d71.gif)
