### ISSUE TITLE
Better pdb support

### ISSUE THREAD

**Issue by mistguy** [nteract/hydrogen#420]
Right now using hydrogen I cannot evaluate enough expressions in pdb prompt since the output is truncated to fit the output window. Is it possible to scroll the output window while pdb is running?

![](http://imgur.com/tF7TC0v.png)

**Comment by rgbkrk** [comment]
Curiosity - we handle stdin now, how does ipdb look in Hydrogen?

**Comment by mistguy** [comment]
![image](https://cloud.githubusercontent.com/assets/8522036/18039468/e611e2ae-6dd5-11e6-843e-35366f371d1b.png)

**Comment by lgeiger** [comment]
Here are the problems with the current implementation:
- If multiple inputs are requested in a row (like pdb does) there is no new ResultView constructed and the results are just appended to the bottom.
- The input view obstructs the editor so no scrolling is possible.

At the moment I don't see a easy fix for this.
Creating a new ResultView for every output of pdb isn't really possible with the current implementation and would need quite a bit of refactoring. 

Somehow allowing scrolling behind the InputView would work but we need to make sure users don't delete the ResultView otherwise there would be no view to append the pdb output to.

**Comment by lgeiger** [comment]
For using `pdb` i would recommend [`hydrogen-launcher`](https://atom.io/packages/hydrogen-launcher) which can spawn a new terminal with a `jupyter console` connected to the running Hydrogen kernel. This way you can use the interactive debugger in the `jupyter console`.

**Comment by lgeiger** [comment]
Since #835 the result view autoscrolls to the bottom. Having a separate input view instead of the overlay would be better but at least it's usable now.
