### ISSUE TITLE
Kernel status indicator fails to update, click does not find running kernels

### ISSUE THREAD

**Issue by kescobo** [nteract/hydrogen#426]
This just started when I upgraded to 0.13

When I restart the python kernel, the indicator remains indefinitely on "Starting." Once I start running code, the transitions between "running" and "idle" seem to function correctly.

![screen shot 2016-08-31 at 12 51 12 pm](https://cloud.githubusercontent.com/assets/3502975/18138214/a83c8d12-6f79-11e6-9142-d29e05ae16b0.png)

Also, when I click the indicator, it does not properly list kernel commands (like interrupt and restart):

![screen shot 2016-08-31 at 12 43 37 pm](https://cloud.githubusercontent.com/assets/3502975/18138136/5b4d983e-6f79-11e6-8f8d-6fe6274848ed.png)

![screen shot 2016-08-31 at 12 43 45 pm](https://cloud.githubusercontent.com/assets/3502975/18138145/5fa90bac-6f79-11e6-8368-579c8ed05db1.png)

Using the command pallet to restart or interrupt works fine.

**Comment by lgeiger** [comment]
> When I restart the python kernel, the indicator remains indefinitely on "Starting." Once I start running code, the transitions between "running" and "idle" seem to function correctly.

We initialize the status bar with `Kernel: starting` but jupyter does not send a status message when the kernel is started completely. 

@rgbkrk @n-riesco Should we simply initialize the status bar with `Kernel: started` since it is created on construction of the [`Kernel` class](https://github.com/nteract/hydrogen/blob/master/lib/kernel-manager.coffee#L118) after the process was spawned?

---

> Also, when I click the indicator, it does not properly list kernel commands (like interrupt and restart):

This is interesting. The status bar is working for me just fine on macOS `10.11.6` and Atom version `1.9.9` or `1.10.0`.

Lets try debugging this:
- Could you open the dev console (by pressing `shift-ctrl-i`) and post an screenshot after trying to open the kernel commands?
- Which atom version are you using?
- Does it happen every time you click on the status bar?

**Comment by rgbkrk** [comment]
> Should we simply initialize the status bar with Kernel: started since it is created on construction of the Kernel class after the process was spawned?

I would, though I'd probably send a `kernel_info_request` and make sure you get a `kernel_info_reply` within reasonable time. Might even want to send several requests after a delay to give the kernel time to start up.

**Comment by kescobo** [comment]
>We initialize the status bar with Kernel: starting but jupyter does not send a status message when the kernel is started completely.

Ahh, apologies - I guess I'd never noticed this before.

>Could you open the dev console (by pressing shift-ctrl-i) and post an screenshot after trying to open the kernel commands?

Nope, 'cause I can't reproduce this now. I updated Atom between posting this issue and your reply - I wasn't that far behind, but apparently that fixed it. Apologies for not doing that first (I didn't notice the little blue squirrel). 

I'll let you close the issue in case you want to keep the other conversation open. Again, sorry for the newb mistake.

**Comment by rgbkrk** [comment]
Okee doke, if it's working then we can go ahead and close this. We can reopen if it comes up again.
