### ISSUE TITLE
Connect to local host kernel

### ISSUE THREAD

**Issue by huyiqun** [nteract/hydrogen#463]
It seems like Hydrogen allows connecting to remote kernel now. I wonder if I can connect to a jupyter notebook kernel e.g. on http://localhost:8888 or a local spyder kernel? I tried to input this url in the gateway configuration, but it does not work out.

**Comment by nikitakit** [comment]
I connect to a local notebook server all the time, on my machine. Here's what my `gateways` setting look like:
```json
[{"name":"Local gateway","options":{"baseUrl":"http://localhost:8888"}}]
```

If you're still having issues getting this working, could you provide more details about what you tried and exactly how it does not work?

**Comment by huyiqun** [comment]
Thanks @nikitakit ! I updated all my packages and tried again today and was able to connect to jupyter notebook kernel from hydrogen! My gateways setting is exactly as what you have above. Weirdly it did not connect the last time.

On the other hand, what I really wanted is to connect to a kernel started in spyder. It does not come with a url address like what notebook does in the browser, so I am not sure what to put in the `baseUrl`. There is `connect_info` that gives an ip address and many port numbers, but that did not work out. Any idea it is possible/how to do this?

**Comment by nikitakit** [comment]
I haven't used Spyder myself, but it seems like spyder is spawning kernels directly instead of through a notebook server.

Connecting to them requires using a different feature of hydrogen. See [here](https://github.com/nteract/hydrogen#custom-kernel-connection-inside-docker) (except ignoring all the stuff about docker).

Essentially, you need to add a `hydrogen/connection.json` file in your project folder (the top folder you added in the tree view), and make sure this file contains the output of `connect_info`. Then hydrogen will connect to that kernel instead of spawning its own.

**Comment by huyiqun** [comment]
Worked like a charm! Thank you so much!!!
