### ISSUE TITLE
Remote kernels

### ISSUE THREAD

**Issue by fsausset** [nteract/hydrogen#482]
It seems impossible to have two remote kernels (on the same jupyter gateway) connected simultaneously for different python files opened in Atom.
I'm using the last version of hydrogen (0.15).

**Comment by nikitakit** [comment]
This is actually by design. Sometimes you want multiple files to be associated with the same kernel. To allow for this use-case, hydrogen only uses one kernel per language (regardless of how many files you have open).

You can still open a new atom window, which will have a separate set of kernels. Alternatively, remote kernels allow you to disconnect from one and then reconnect to it later.

Both the single-kernel-multi-file and multi-kernel use cases are important, and I can't come up with a better compromise between the two workstyles.

**Comment by fsausset** [comment]
I'm quite new to Hydrogen and didn't noticed that kernels are per window.
This behaviour is fine! :-)
