### ISSUE TITLE
Have inline result problem.

### ISSUE THREAD

**Issue by Iniyan-S** [nteract/hydrogen#570]
As installed ipython3 from Ubuntu software centre alone not jupyter. When tried to use it with Hydrogen. Nothing shows up. (Added `{
  "kernelspecs": {
    "python3": {
      "spec": {
        "display_name": "Python 3",
        "language": "python",
        "argv": ["python3.4", "-m", "ipykernel", "-f", "{connection_file}"],
        "env": {}
      }
    }
  }
}`
in the Kernel Specs field). While running the code this is what appears next to the code.
![ipython](https://cloud.githubusercontent.com/assets/10035395/21587373/bb15f9b6-d101-11e6-8f84-8f0f6f2afa09.png)
Kindly need your help.

**Comment by lgeiger** [comment]
What version of python are you trying to use inside Hydrogen?

My guess is that `python3.4` (as mentioned in the kernel spec) is the wrong executable.

**Comment by Iniyan-S** [comment]
Hi, Thanks for the reply.
I am using Ubuntu 14.04 / Atom 1.12.7 and python versions in m/c are Python 2.7.6 & 3.4.3.

![python versions](https://cloud.githubusercontent.com/assets/10035395/21633516/ec3e910e-d275-11e6-9382-3027fd2c9a98.png)
![python locations](https://cloud.githubusercontent.com/assets/10035395/21633519/f2a7a09e-d275-11e6-893e-e8cb43cf6c51.png)
Updated the Kernel Specs field with `{
  "kernelspecs": {
    "python2": {
      "spec": {
        "display_name": "Python 2",
        "language": "python",
        "argv": ["python2.7", "-m", "ipykernel", "-f", "{connection_file}"],
        "env": {}
      }
    },
    "python3": {
      "spec": {
        "display_name": "Python 3",
        "language": "python",
        "argv": ["python3.4", "-m", "ipykernel", "-f", "{connection_file}"],
        "env": {}
      }
    }
  }
}`
Even tried installing JUPYTER using anaconda3 along in different location '/opt/anaconda3' but couldn't resolve the issue yet.

**Comment by Iniyan-S** [comment]
Now i have resolved the issue. After lil digging i found that actually i had to update my kernelspec code field with the following,`{
  "kernelspecs": {
    "python3": {
      "spec": {
        "argv": [
          "/opt/anaconda3/bin/python",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ],
        "display_name": "Python 3",
        "language": "python",
        "env": {}
      },
      "resource_dir": "/opt/anaconda3/lib/python3.5/site-packages/ipykernel/resources"
    }
  }
}
`

**Comment by linamnt** [comment]
Sorry to bring up a closed issue but I think my issue is related. I was having trouble with inline usage in any file whereby running a line would start a Python process in the bg that was using lots of memory and would never end unless I manually killed process. I used @Iniyan-S solution and worked on most files. 

But on the specific project folder I'm working on, if I ran hydrogen inline, still would not work and cause new python process again as above. It's not anything about the python files themselves, because if I copy and paste the same code but put it in another folder, it works fine.

Not sure what it is in this folder that could cause this?
