### ISSUE TITLE
MagicPython still not working

### ISSUE THREAD

**Issue by michaelaye** [nteract/hydrogen#580]
#I'm starting Atom from a Python3 conda env with everything installed for a jupyter notebook environment.
I also added

{"python" : "magicpython"}

to the Language Mappings, but still receive the following error:

![screenshot 2017-01-10 17 56 12](https://cloud.githubusercontent.com/assets/69774/21831028/19775100-d75e-11e6-87b4-2b1f2eebab23.png)

I did not change anything else in the hydrogen config, and it was installed via apm, version 1.5.2 on OSX 10.11.6, with Atom 1.13.0

**Comment by nikitakit** [comment]
I had magicpython working earlier, and the setting I had was `{"python":"magicpython"}` (I think switching the key and value should be sufficient to fix your problem.)

But I found bug #465 very annoying, so I ended up uninstalling magicpython a while back. Not sure what the hydorogen+magicpython compatibility story is nowadays.

**Comment by lgeiger** [comment]
I just tried `{"python":"magicpython"}` and it works for me.

Could you post a screenshot of your Hydrogen settings?

**Comment by michaelaye** [comment]
There you go:
![screenshot 2017-01-12 10 33 50](https://cloud.githubusercontent.com/assets/69774/21900858/a580724e-d8b2-11e6-9c80-0f9662f3fcaa.png)

**Comment by michaelaye** [comment]
Note that I use nb_conda_kernels for automatic ipykernel detection, so I don't have kernel path files to point to kernels, could that be a problem?

**Comment by michaelaye** [comment]
No, the missing ipykernel path files are not the problem, I just switched to atom's default python and hydrogen works there.

**Comment by lgeiger** [comment]
You forgot a quote ;)

Use `{"python":"magicpython"}` instead of `{"python:"magicpython"}`.

**Comment by michaelaye** [comment]
oh, darn. sorry for the noise. Works! Thanks a lot *ducking_outta_here_fast* :/

**Comment by lgeiger** [comment]
:joy: No problem! I'm glad it's working :+1:

**Comment by blokeley** [comment]
I can't get this working at all.  I'm not missing quotes.

I've tried everything:
{"MagicPython": "python"}
{"magicpython": "python"}
{"python": "magicpython"}

The Hydrogen Kernel Monitor always says, "No running kernels", and if I try "Start Local Kernel", I just get "no kernels found"

Versions:
Atom 1.22.1
Hydrogen 2.1.0
Python 3.6.2
ipython 6.1.0
jupyter 1.0.0
Windows 10

**Comment by lgeiger** [comment]
Have you followed the kernel installation instructions at https://nteract.io/kernels/python?

**Comment by blokeley** [comment]
I followed those instructions but no change (I think I had done them before, some months ago anyway).

This is what I did:

1. Install the kernel as per your link above.
2. Open Atom.
3. Create a new file.
4. Use the Grammar Selector to change to MagicPython.
5. Write some dummy code, for example "print('hello')".
6. Type Ctrl+Enter.

Nothing happens.
Kernel Monitor says No running kernels.
Update Kernels brings up a blue box saying "Python 3".
Start Local Kernel says "No kernels found"

I thought that maybe the file had to be saved to disk, then I managed to get a kernel going on a saved file using the language mapping `{"python": "magicpython"}`.

Maybe I found the bug:
* Hydrogen works when I open an existing Python file, but 
* Not when I create a new file then save it.
* Not when I create a new file which has not yet been saved to disk.

I used to use the latter case (use new "buffers" i.e. unsaved files) as temporary ipython consoles.

Please could you list the steps from opening Atom onwards that should get it working?  I used to use Hydrogen a lot many months ago and it seemed to just work, but I can't get it working now that I use MagicPython (which I have to use because I use mypy and f-strings a lot).

Thanks in advance for any help.
