### ISSUE TITLE
I use 'run-all' get two kinds of result

### ISSUE THREAD

**Issue by wlccgp3** [nteract/hydrogen#582]
```python
#! /usr/bin/python3
# coding:utf-8

@foo
def hello():
    return 'hello world'

def foo(func):
    def bar():
        return "<i>" + func() + "</i>"
    return bar

hello()       #--> '<i>hello world</i>'
```

we know this code was wrong, but I use "Run-All", get this: `'<i>hello world</i>'`.
so I try use "Run-All-Above", It return right result(NameError).

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-a452b6a29fb7> in <module>()
      2 
      3 
----> 4 @foo
      5 def hello():
      6     return 'hello world'

NameError: name 'foo' is not defined
```
and after that I close atom and use "Run-All", It can be work, return(NameError)
But next time, I can't confirm it that the code was right or wrong

**Comment by lgeiger** [comment]
Hydrogen executes code in the same python instance to enable a interactive coding experience.

In your case this means if you run the code for the first time it will throw a error since `@foo` isn't defined.

If you now run only
```python
def foo(func):
    def bar():
        return "<i>" + func() + "</i>"
    return bar
```
by selecting it and then execute the whole file, it will work since `@foo` is already defined in the python instance.

To start with a fresh python instance, click on the kernel name in the status bar and restart the kernel.

**Comment by wlccgp3** [comment]
oh, I thought "run all" was F5 like python idle before.
I get it now.thank you very much.
