### ISSUE TITLE
Store Output Results 

### ISSUE THREAD

**Issue by lolokazaki** [nteract/hydrogen#615]
Hi,

In Jupyter notebook whenever you close and re open notebook all your local output and results are saved so you don't have to re run all the cells again to see the results,  I was wondering whether the same thing is possible for hydrogen ? 

Thanks

**Comment by lgeiger** [comment]
I don't think this is possible for us to do in a clean way, apart from needing auxiliary files, in Hydrogen one can run single lines or even just small pieces of the code which would make it confusing what results to store.

This is the use case where notebooks shine, since the output is saved in the `json` notebook file. You might want to try out [nteract](https://github.com/nteract/nteract).
