### ISSUE TITLE
Where is hydrogen documentation?

### ISSUE THREAD

**Issue by abalter** [nteract/hydrogen#630]
I can't seem to find any documentation or tutorials about how to use hydrogen. It uses many ideas from ipython/jupyter, but it is not the same. 

Example:
   %%bash

shift-enter gives: "UsageError: %%bash is a cell magic, but the cell body is empty."

    %%bash
    ls

shift-enter give directory listing

    %%bash
    a=10

shift-enter puts a check mark by `a=10`

    %%bash
    a=10
    echo $a

shift-enter gives 

```
File "<ipython-input-29-54540ec9478a>", line 1
    echo $a
         ^
SyntaxError: invalid syntax
```

I cannot find a guide for how to understand this behavior, or in general how to use hydrogen.

**Comment by lgeiger** [comment]
@abalter You're right our documentation is a bit sparse at the moment. Contributions are highly welcome 😄 🎉 

[Cell magics](http://ipython.readthedocs.io/en/stable/interactive/magics.html#cell-magics) like `%%bash` or anything else beginning with `%%` inside a notebook apply to a block of code below them, therefor the first command fails if only the line with the cell magic is executed.
On the other hand only executing `echo $a` will fail since the python interpreter doesn't know about the cell magic above and that it should be a `bash` command. Instead it assumes you're trying to execute `python` code.

If you want to use them make sure to execute the desired code together with the cell magic.
For example by selecting the entire block of code or by excuting the whole file. You can find more information about how to do this [here](https://github.com/nteract/hydrogen#usage).

**Comment by BenRussert** [comment]
@abalter have you seen the newly added [gitbook](https://nteract.gitbooks.io/hydrogen/content/)?
