### ISSUE TITLE
Connect kernel automatically when atom starts

### ISSUE THREAD

**Issue by PradeepJaiswar** [nteract/hydrogen#638]
I have my kernels installed on remote server. My workflow involves using only one kernel which is IPython. Now i have to select my kernel manually each time i start my atom.

How can i connect to kernel (IPython) automatically when my atom starts ? 

Please suggest if it requires any changes to hydrogen package code as i am forking and using it.
Thanks

**Comment by BenRussert** [comment]
A keyboard shortcut would not be quick enough for you?

I think this is a pretty specific use case. If you really want this behavior every single time you launch atom try hacking your init script. Check out [the dispatch method](url) from the CommandRegistry atom API docs. You could probably hack something in your init.coffee to make this work, i'm not sure.

I have to say I really think you are better off setting up a custom keybinding so you are always in control of what happens when you start atom.
