### ISSUE TITLE
Long Error Messages

### ISSUE THREAD

**Issue by JLCCI** [nteract/hydrogen#659]
First of all, thanks so much for your work on Hydrogen. It works brilliantly and it's so much easier to code vs. Jupyter notebook in a browser.

I have two quick questions regarding big output windows.
 
![screenshot from 2017-03-23 14-50-14](https://cloud.githubusercontent.com/assets/18163728/24233847/06d5126e-0fd8-11e7-9794-99c037765eac.png)

1) The output window is narrower when minimap is on, but for people with minimap autohider, the window overlaps with the minimap when it is visible. Any way to force the window to always be narrower even if minimap is set to autohide?

2) I used the code below to disable scrollbars (don't find them useful at all) but it also disables scrollbar in the Hydrogen output. Any tweaks/shortcuts to scroll down to the bottom of a long message without the scrollbar? Not sure how much work it would be to add a button to do this.

`::-webkit-scrollbar {
    display: none;
}`

Many thanks for your help!

**Comment by lgeiger** [comment]
> The output window is narrower when minimap is on, but for people with minimap autohider, the window overlaps with the minimap when it is visible. Any way to force the window to always be narrower even if minimap is set to autohide?

We set the width [here](https://github.com/nteract/hydrogen/blob/master/lib/main.js#L270). We cannot use CSS here because the width would be relative to the longest line and not to the visible part of the editor.
We would need to listen for changes to the editor width but I don't know if this is possible. Atom itself doesn't provide a API to listen for width changes. 

> I used the code below to disable scrollbars (don't find them useful at all) but it also disables scrollbar in the Hydrogen output. Any tweaks/shortcuts to scroll down to the bottom of a long message without the scrollbar?

You can always use the mouse wheel to scroll, even if the scrollbars are hidden.
Or you can add
```less
::-webkit-scrollbar { display: none; }
.hydrogen {
  ::-webkit-scrollbar { display: block; }
  }
```
to enable them only for hydrogen.

**Comment by JLCCI** [comment]
Ow I see, guess it's either not having minimap or not hiding it. Thought it would be easy to make it behave as if minimap was always on.

And thank you for the code!
