### ISSUE TITLE
"reload(sys)" Caused the Print Results to Disappear

### ISSUE THREAD

**Issue by lleiou** [nteract/hydrogen#697]
**Description:**

It is until recently that I came to realize that Hydrogen should show the print result in the bubble.....From the beginning till today, I can only see a `√` in the bubble...After following the solutions posted by other users, namely `brew install zeromq`, I can get the print results showed from time to time, but not always. Finally, after doing the following 3 steps, I found the cause......

**Steps to Reproduce:**

1. > print("this is normal")

2. > reload(sys)
    > sys.setdefaultencoding('utf-8')

3. > print("this is abnormal")

**Versions:**

`$ apm --version`
`apm  1.15.3`
`npm  3.10.5`
`node 4.4.5 x64`
`python 2.7.11`
`git 2.8.4`

`$ ipython --version`
`4.1.2`
`

![screen shot 2017-04-04 at 11 18 25 pm](https://cloud.githubusercontent.com/assets/3372200/24688412/d13bdc72-198d-11e7-8d9d-7758e23b4634.jpg)

**Comment by lgeiger** [comment]
Since version 1.0 `brew install zeromq` won't have any effect anymore, since we bundle all dependencies for easy install. You can safely uninstall it again.
I'll try to reproduce this later today.

**Comment by lgeiger** [comment]
`sys.setdefaultencoding` was removed in Python 3 and is not recommended to use in Python 2 either.
For more information see: http://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script

`jupyter notebook` shows the same behavior since after reloding the output is forwarded to `stdout` and not sent to the frontend. This issue won't be fixed in ipython (https://github.com/ipython/ipython/issues/8354).

I would recommend using Python 3. As far as I know it uses `utf-8` by default.

**Comment by lleiou** [comment]
@lgeiger Thank you very much for your reply! Yes you are right, I use python 2, that's why I got the error. 
Apart from switching to Python 3, I found another [solution](http://stackoverflow.com/a/23847316/5861873) on Stack Overflow:
`import sys
stdin, stdout, stderr = sys.stdin, sys.stdout, sys.stderr
reload(sys)
sys.stdin, sys.stdout, sys.stderr = stdin, stdout, stderr`
