### ISSUE TITLE
Python 3 | IPKernelApp ERROR Invalid Message Traceback

### ISSUE THREAD

**Issue by JayZ2398** [nteract/hydrogen#750]
**Description:**

This is an issue I managed to resolve, but I'm posting it here in case it helps anyone else.
I was playing around for ages trying to get Hydrogen working in Atom on Windows 10, but kept getting an error message along the lines of:
IPKernelApp ERROR Invalid Message Traceback...Invalid Signature

I'd installed jupyter through elevated command prompt using pip, i.e:
pip install jupyter
And then installed Hydrogen through the command:
apm install hydrogen

Eventually, I (think I) uninstalled both kernels/packages via:
pip uninstall jupyter
apm uninstall hydrogen

I managed to **get Hydrogen to work by reinstalling jupyter with Anaconda.** To do this, I had to download Anaconda from https://www.continuum.io/downloads, and then run the commands:
conda update conda
conda update anaconda
And finally, I ran:
conda install jupyter
apm install hydrogen

That did the trick for me, happily Hydrogen-ing now. Let me know if this helps anyone, or if you know why this error might've occurred in the first place when I installed jupyter through pip. I apologise for not having the error logs, as I didn't keep a record of them.

I'd seen this error posted by a MacOS user under this thread (https://github.com/nteract/hydrogen/issues/674), but given my issue occurred on Windows and was resolved differently, I figured I'd make another post.

**Steps to Reproduce:**

1. [First Step]
2. [Second Step]

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

Atom: 1.16.0
Electron: 1.3.13
Chrome: 52.0.2743.82
Node: 6.5.0

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by rgbkrk** [comment]
That definitely sounds like a bad zeromq installation which was resolved by installing the anaconda binary install. Thanks for providing the error and your workaround.

**Comment by dancbart** [comment]
I was getting the same traceback error and I fixed it by just doing the first step of the procedure, i.e. reinstalling Jupiter with pip as follows:

pip install Jupiter

after this I re-ran the code (ctrl-cmd-enter) and it worked fine.

HOWEVER: I did the "pip install jupiter" in the terminal window that I used to activate the virtual environment that I originally put the Jupiter kernel into.  In case it helps anyone, in order to activate a virtual environment, type:

source my.environ/bin/activate

where "my.environ" is whatever you've named your virtual environment.  As an example, on my Mac (Big Sur) here is what the file path looks like (don't forget the / at the beginning):

/users/myname/my.environ/bin/activate

Once you type "source my.environ/bin/activate" into the terminal, and press enter, your command prompt will look different, in the above example, it would look something like this:

(my.environ) myname-MacBook_Pro:/ myname$

**Notice the (my.environ) preceding the stuff you normally see at the comment prompt.  That tells you you're in the virtual environment and that it's been successfully activated.

FINALLY: I ran the "pip install Jupiter" as indicated above from the command prompt of the activated virtual environment: (my.environ) myname-MacBook_Pro:/ myname$

I say all this because It's always confusing where to run things from (inside the virtual environment, outside of it, in your user directory, in your .git, whatever).  I'm not 100% that the way I did it in the virtual env.'s command prompt was the right way, except that it did fix the problem.

Please feel free to reply if you have better info as far as installing from the regular command line, or the virtual environment's command line.

I am using Atom 1.54.0 x64
