### ISSUE TITLE
Restarting kernel with external output area hides entire UI area

### ISSUE THREAD

**Issue by wowserx** [nteract/hydrogen#849]
**Description**

When the kernel is restarted, the UI area containing the external output area (EOA) is hidden. 

For example, if the EOA is in the same UI element as the project path view, either as a tab:

<img width="310" alt="screen shot 2017-06-02 at 18 43 35" src="https://cloud.githubusercontent.com/assets/29137805/26747411/9067ae42-47c3-11e7-9b69-90071157a11a.png">

or above or below in the same sidebar:

<img width="308" alt="screen shot 2017-06-02 at 18 44 00" src="https://cloud.githubusercontent.com/assets/29137805/26747423/9fbb57ea-47c3-11e7-9069-44824bd715cc.png">

Restarting the kernel will hide the 'project' tab. 

[Here are (I'm pretty sure) the lines that cause this behavior.](https://github.com/nteract/hydrogen/pull/825/files#diff-06c78041ac8e1eb79621efd8c87dc106R13)

Does hiding the EOA, in this context, serve a purpose? If it is, could it be configurable in settings? Having to re-open sidebars every time I restart the kernel is a little annoying.

**Comment by lgeiger** [comment]
The sidebar gets only hidden when the output area is the active tab inside the dock. We do this since the panel wouldn't show anything useful if no kernel is running. Therefor we hide it to don't waste any space which is particular useful for smaller screens.

The panel will automatically appear if one executes output though. So there shouldn't be the need for manually re-opening the sidebar.

That said, maybe we should rethink the way we currently restart our ZMQ kernels. Right now we basically destroy the old one and start a fresh kernel. I think for the kernel process we still need to do this, but we probably don't need to dispose the whole kernel class (which causes the panel to hide).

**Comment by wowserx** [comment]
Thanks for responding! 

So it's intended behavior for shutting down the kernel, but not necessarily for restarting.

Would it be too cruft-y to add an 'isRestarting' flag, and check `!kernel && !isRestarting` rather than just `!kernel ` ? It might be quicker+safer to implement than changing the behavior of the kernel class. 

I realize it's a small problem, but having the code area jump left or right, or having to re-open the project tab when it was visible pre-restart, is a little jarring.

**Comment by rgbkrk** [comment]
> That said, maybe we should rethink the way we currently restart our ZMQ kernels. Right now we basically destroy the old one and start a fresh kernel. I think for the kernel process we still need to do this, but we probably don't need to dispose the whole kernel class (which causes the panel to hide).

Yeah, we could even keep the same connection file and ports (assuming the other kernel hasn't run away). ZeroMQ will automatically reconnect.

**Comment by lgeiger** [comment]
Should we reset the output in the output area if a kernel is restarted?

**Comment by rgbkrk** [comment]
I'd be inclined to keep it if it's _only_ a restart, making the output clearing a separate thing. Restart and clear all could be a separate action.
