### ISSUE TITLE
Question: How can one execute R code with hydrogen?

### ISSUE THREAD

**Issue by hugeme** [nteract/hydrogen#881]
I recently switched from R to Python and in that respect found hydrogen as my go-to-package for data analysis. I just read your blog post: [https://blog.nteract.io/hydrogen-interactive-computing-in-atom-89d291bcc4dd](url), where you reference the possibility to run R code with hydrogen as well. May I ask you how to add this ability to hydrogen?
Thx.

**Comment by BenRussert** [comment]
Hydrogen is my go to as well! 

There is some info on other kernels [in our gitbook](https://nteract.gitbooks.io/hydrogen/docs/Installation.html)

Basically you need to install the ir kernel. Make sure you have `r-language` package installed for atom as well since there is no R support in atom by default.

**Comment by hugeme** [comment]
Hi @BenRussert, thx for your quick reply. I just followed [https://irkernel.github.io/installation/](url) and installed `r-language`.  Do I have to add that new infos to hydrogen somehow?

**Comment by BenRussert** [comment]
It should work without the custom kernel mapping for ir, magicpython needs the mapping since it would start an ordinary python kernel by default.

> So initializing hydrogen starts both Kernels. Question remains how to switch between them.

If you have R file active it will start R. If you switch tabs to a python file and start a kernel there it will be python (magicpython in your case). Both will run until you shut down and you can tab back and forth as you please interacting with either kernel.

**Comment by hugeme** [comment]
@BenRussert thats super cool. everything is working as you have pointed out, thx!

**Comment by BenRussert** [comment]
@hugeme No prob. If there is anything you think could be better/clearer in the docs we would love a PR with your suggestions!
