### ISSUE TITLE
Regression: connecting to a kernel from one tab now connects another tab to the same kernel

### ISSUE THREAD

**Issue by maximsch2** [nteract/hydrogen#884]
**Description:**

Connecting to a kernel from one tab now connects another tab to the same kernel

**Steps to Reproduce:**

1. Open file A, connect to a remote kernel through gateway, run some code
2. Open file B in another tab, connect to a different kernel, run some code
Expected: file A is still connected to it's original kernel
Instead: file A is now connected to B's kernel

**Versions:**
Atom 1.18, Hydrogen 1.17.1

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by BenRussert** [comment]
What kernels are you running in each editor? If you are talking about the same [grammar](http://flight-manual.atom.io/using-atom/sections/grammar/) in each editor, I dont recall there being a way to connect to multiple kernels with the same grammar.

**Comment by maximsch2** [comment]
Yes, two different kernels with the same grammar used to work as of a couple of weeks ago, an update to one of the latest releases broke it.

**Comment by nikitakit** [comment]
@maximsch2 I'm surprised you were getting a different behavior previously, because having all tabs with the same grammar share a kernel has always been the intended behavior. For over a year now I've been interacting with the same kernel from multiple files, and I've never been able to have two different kernels open with the same grammar.

The way it works is that tabs in the same window share a kernel, but no kernels are shared across multiple windows or Atom instances.

I am curious exactly what caused a change in behavior though. Which hydrogen version were you running previously?

**Comment by JGH1000** [comment]
Would having more than one kernel with the same grammar, in the same window, possible? That would be really great if yes.

**Comment by maximsch2** [comment]
@nikitakit, I'm pretty sure it used to work before, although I can't reproduce it now with rolling back either Hydrogen or  Atom... Maybe something odd was going on in my particular configuration.

That being said, having an ability to attach separate kernels to separate files would be a great feature to have! Closing this in favor of #40 then.
